<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.1
 */

/**
 * Database `e-commerce-sql`
 */

/* `e-commerce-sql`.`address` */
$address = array(
  array('id_address' => '1','id_user' => '1','street' => '4425 Mathew Hill Suite 230','city' => 'Noefort','postal_code' => '93447-7100','country' => 'Sao Tome and Principe'),
  array('id_address' => '2','id_user' => '2','street' => '583 Jacobs Trafficway Apt. 713','city' => 'Port Isac','postal_code' => '90365-6935','country' => 'Canada'),
  array('id_address' => '3','id_user' => '3','street' => '449 Josiane Loop','city' => 'Boehmmouth','postal_code' => '83905-6000','country' => 'Philippines'),
  array('id_address' => '4','id_user' => '4','street' => '29209 Jeanette Circle','city' => 'South Kristyfurt','postal_code' => '72079-0359','country' => 'France'),
  array('id_address' => '5','id_user' => '5','street' => '868 Natasha Divide','city' => 'North Skylar','postal_code' => '79762-9461','country' => 'Uzbekistan'),
  array('id_address' => '6','id_user' => '6','street' => '759 Shea Overpass Apt. 992','city' => 'Lake Trenton','postal_code' => '71072','country' => 'Saudi Arabia'),
  array('id_address' => '7','id_user' => '7','street' => '04888 Hahn Spring','city' => 'North Glenmouth','postal_code' => '42028-9740','country' => 'Gibraltar'),
  array('id_address' => '8','id_user' => '8','street' => '268 Kshlerin Spurs','city' => 'New Vena','postal_code' => '50612','country' => 'Paraguay'),
  array('id_address' => '9','id_user' => '9','street' => '052 Ray Lodge Apt. 614','city' => 'Romagueramouth','postal_code' => '20505','country' => 'Denmark'),
  array('id_address' => '10','id_user' => '10','street' => '2782 Leanne Shores Suite 234','city' => 'North Dena','postal_code' => '53122-3350','country' => 'South Africa'),
  array('id_address' => '11','id_user' => '1','street' => '268 Rose Mount Suite 704','city' => 'Port Nya','postal_code' => '82174','country' => 'Equatorial Guinea'),
  array('id_address' => '12','id_user' => '2','street' => '615 Rau Mews','city' => 'West Shannon','postal_code' => '96425-2637','country' => 'Lesotho'),
  array('id_address' => '13','id_user' => '3','street' => '2893 Rutherford Plaza Suite 716','city' => 'Port Carmine','postal_code' => '17482','country' => 'Chad'),
  array('id_address' => '14','id_user' => '4','street' => '012 Mariela Roads Suite 065','city' => 'Swaniawskiview','postal_code' => '63278','country' => 'Cocos (Keeling) Islands'),
  array('id_address' => '15','id_user' => '5','street' => '823 Bosco Mountains','city' => 'Cieloton','postal_code' => '68692-5490','country' => 'Reunion'),
  array('id_address' => '16','id_user' => '6','street' => '520 Liliana Station Apt. 187','city' => 'Jaynestad','postal_code' => '23537-2003','country' => 'Thailand'),
  array('id_address' => '17','id_user' => '7','street' => '114 Jesse Mountain Suite 076','city' => 'North Jacinthe','postal_code' => '35303','country' => 'Brunei Darussalam'),
  array('id_address' => '18','id_user' => '8','street' => '819 Lonny Island','city' => 'South Vince','postal_code' => '15474-4190','country' => 'Netherlands Antilles'),
  array('id_address' => '19','id_user' => '9','street' => '388 Bode Oval Apt. 460','city' => 'Oberbrunnermouth','postal_code' => '56124','country' => 'Turkmenistan'),
  array('id_address' => '20','id_user' => '10','street' => '554 Langworth Mountain Suite 125','city' => 'West Tessie','postal_code' => '10696-3350','country' => 'Saint Lucia'),
  array('id_address' => '21','id_user' => '1','street' => '74881 Torp Forges Apt. 294','city' => 'Bennybury','postal_code' => '28162','country' => 'Botswana'),
  array('id_address' => '22','id_user' => '2','street' => '16703 Carter Place Apt. 457','city' => 'Ethelmouth','postal_code' => '29580','country' => 'Turkmenistan'),
  array('id_address' => '23','id_user' => '3','street' => '479 Lafayette Walks','city' => 'South Vicky','postal_code' => '51452-4072','country' => 'Palau'),
  array('id_address' => '24','id_user' => '4','street' => '49080 Howe Track','city' => 'Blickview','postal_code' => '18075','country' => 'Latvia'),
  array('id_address' => '25','id_user' => '5','street' => '127 Nolan Throughway Apt. 828','city' => 'Lizaton','postal_code' => '16094','country' => 'Venezuela'),
  array('id_address' => '26','id_user' => '6','street' => '44320 Erdman Stravenue Suite 018','city' => 'Port Gideon','postal_code' => '26175','country' => 'Timor-Leste'),
  array('id_address' => '27','id_user' => '7','street' => '3553 Eloise Spring Apt. 501','city' => 'South Enrique','postal_code' => '17819-1499','country' => 'Faroe Islands'),
  array('id_address' => '28','id_user' => '8','street' => '4531 Garry Station Apt. 850','city' => 'North Dahlia','postal_code' => '16353','country' => 'Cambodia'),
  array('id_address' => '29','id_user' => '9','street' => '16025 Yundt Wells','city' => 'Lake Brandyn','postal_code' => '32708','country' => 'Burkina Faso'),
  array('id_address' => '30','id_user' => '10','street' => '0375 Queenie Cliffs Apt. 228','city' => 'Blairburgh','postal_code' => '87274','country' => 'Romania'),
  array('id_address' => '31','id_user' => '1','street' => '4837 Lolita Forest','city' => 'Jacquesport','postal_code' => '71696','country' => 'Hungary'),
  array('id_address' => '32','id_user' => '2','street' => '5893 Narciso Brooks','city' => 'Chrisshire','postal_code' => '71145-7251','country' => 'Belize'),
  array('id_address' => '33','id_user' => '3','street' => '247 Luettgen Throughway Apt. 135','city' => 'Runolfssonville','postal_code' => '42807-9637','country' => 'Zimbabwe'),
  array('id_address' => '34','id_user' => '4','street' => '737 Carroll Lodge Apt. 770','city' => 'South Ivy','postal_code' => '24625-7065','country' => 'Aruba'),
  array('id_address' => '35','id_user' => '5','street' => '5398 Tressa Harbor','city' => 'Judgestad','postal_code' => '65552-3353','country' => 'Greenland'),
  array('id_address' => '36','id_user' => '6','street' => '37019 Johann Vista','city' => 'Kuhicstad','postal_code' => '36238','country' => 'Dominican Republic'),
  array('id_address' => '37','id_user' => '7','street' => '003 Bergnaum Turnpike','city' => 'Feltonfort','postal_code' => '78915-2099','country' => 'Russian Federation'),
  array('id_address' => '38','id_user' => '8','street' => '338 Hettinger Track','city' => 'Port Santiagoburgh','postal_code' => '54509-0669','country' => 'Nepal'),
  array('id_address' => '39','id_user' => '9','street' => '74697 Parisian Brooks','city' => 'Weissnatstad','postal_code' => '53760','country' => 'Western Sahara'),
  array('id_address' => '40','id_user' => '10','street' => '86689 Nicklaus Parkway','city' => 'Eastertown','postal_code' => '60397-3739','country' => 'British Indian Ocean Territory (Chagos Archipelago)'),
  array('id_address' => '41','id_user' => '1','street' => '83175 Champlin Views Apt. 138','city' => 'Lindhaven','postal_code' => '70263-3294','country' => 'Lithuania'),
  array('id_address' => '42','id_user' => '2','street' => '12389 Helga Tunnel Suite 461','city' => 'New Einomouth','postal_code' => '87237-0327','country' => 'Gibraltar'),
  array('id_address' => '43','id_user' => '3','street' => '60306 Bauch Walk','city' => 'Charlotteburgh','postal_code' => '81401','country' => 'Luxembourg'),
  array('id_address' => '44','id_user' => '4','street' => '4989 Clyde Village Suite 522','city' => 'East Joshuah','postal_code' => '40019-6444','country' => 'Ireland'),
  array('id_address' => '45','id_user' => '5','street' => '91134 Kristopher Ports','city' => 'North Clotilde','postal_code' => '77252','country' => 'Saudi Arabia'),
  array('id_address' => '46','id_user' => '6','street' => '85613 Kylie Union Suite 770','city' => 'North Taryn','postal_code' => '78988-5143','country' => 'Indonesia'),
  array('id_address' => '47','id_user' => '7','street' => '459 Tara Centers','city' => 'Marianamouth','postal_code' => '99099-6978','country' => 'Slovakia (Slovak Republic)'),
  array('id_address' => '48','id_user' => '8','street' => '563 Rowe Station Suite 463','city' => 'Isabelletown','postal_code' => '04283','country' => 'Greece'),
  array('id_address' => '49','id_user' => '9','street' => '8947 Pfannerstill Lodge Apt. 520','city' => 'Manuelaville','postal_code' => '29404-5825','country' => 'Nigeria'),
  array('id_address' => '50','id_user' => '10','street' => '29195 Ashleigh Lake','city' => 'Ilenemouth','postal_code' => '04116-7788','country' => 'Sweden'),
  array('id_address' => '51','id_user' => '1','street' => '98756 Iva Isle Suite 317','city' => 'Wernerville','postal_code' => '77679','country' => 'Sao Tome and Principe'),
  array('id_address' => '52','id_user' => '2','street' => '85856 Zackary Mews Apt. 328','city' => 'West Charlotte','postal_code' => '57612-9009','country' => 'United States of America'),
  array('id_address' => '53','id_user' => '3','street' => '976 Lou Circle Apt. 277','city' => 'Cruzbury','postal_code' => '89464-2134','country' => 'Azerbaijan'),
  array('id_address' => '54','id_user' => '4','street' => '2809 Corkery Pines Suite 249','city' => 'North Hal','postal_code' => '79571-0902','country' => 'Saint Pierre and Miquelon'),
  array('id_address' => '55','id_user' => '5','street' => '392 Felix Falls Suite 168','city' => 'Schaeferside','postal_code' => '46927','country' => 'Western Sahara'),
  array('id_address' => '56','id_user' => '6','street' => '8258 Hessel Vista','city' => 'East Shanelmouth','postal_code' => '14899-6003','country' => 'Togo'),
  array('id_address' => '57','id_user' => '7','street' => '53237 Pagac Inlet','city' => 'North Briana','postal_code' => '79275-6538','country' => 'Nepal'),
  array('id_address' => '58','id_user' => '8','street' => '984 Estefania Mountains Apt. 769','city' => 'Deonville','postal_code' => '20562-9896','country' => 'Georgia'),
  array('id_address' => '59','id_user' => '9','street' => '53932 Wuckert Neck Suite 443','city' => 'Nathanport','postal_code' => '69881','country' => 'Gabon'),
  array('id_address' => '60','id_user' => '10','street' => '125 Piper Union','city' => 'Port Vicentestad','postal_code' => '06015','country' => 'Czech Republic'),
  array('id_address' => '61','id_user' => '1','street' => '45349 Effertz Plains','city' => 'Xzavierview','postal_code' => '66777','country' => 'Yemen'),
  array('id_address' => '62','id_user' => '2','street' => '97668 Tillman Bypass Apt. 715','city' => 'Lillianabury','postal_code' => '62219','country' => 'Qatar'),
  array('id_address' => '63','id_user' => '3','street' => '12525 Johnston Streets Suite 757','city' => 'Colliermouth','postal_code' => '38852','country' => 'Hungary'),
  array('id_address' => '64','id_user' => '4','street' => '555 Olson Light Suite 151','city' => 'Cassinville','postal_code' => '57928-3680','country' => 'Bangladesh'),
  array('id_address' => '65','id_user' => '5','street' => '874 Thea Summit Suite 866','city' => 'New Raheem','postal_code' => '11756-2860','country' => 'Bosnia and Herzegovina'),
  array('id_address' => '66','id_user' => '6','street' => '123 Patricia Springs Apt. 697','city' => 'Gildaberg','postal_code' => '56156','country' => 'Saudi Arabia'),
  array('id_address' => '67','id_user' => '7','street' => '83712 Tyrel Trace Apt. 321','city' => 'North Arlenestad','postal_code' => '02750','country' => 'New Zealand'),
  array('id_address' => '68','id_user' => '8','street' => '40768 Bernadine Park','city' => 'Port Vince','postal_code' => '02185','country' => 'Slovenia'),
  array('id_address' => '69','id_user' => '9','street' => '1254 Tromp Groves Apt. 891','city' => 'Lyricview','postal_code' => '60028-6314','country' => 'Algeria'),
  array('id_address' => '70','id_user' => '10','street' => '49751 Matilda Union Apt. 627','city' => 'Jenningston','postal_code' => '25127-5963','country' => 'El Salvador')
);

/* `e-commerce-sql`.`cart` */
$cart = array(
  array('id_cart' => '1','id_user' => '1','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '2','id_user' => '2','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '3','id_user' => '3','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '4','id_user' => '4','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '5','id_user' => '5','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '6','id_user' => '6','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '7','id_user' => '7','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '8','id_user' => '8','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '9','id_user' => '9','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '10','id_user' => '10','created_at' => '2024-10-12 00:02:30'),
  array('id_cart' => '11','id_user' => '1','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '12','id_user' => '2','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '13','id_user' => '3','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '14','id_user' => '4','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '15','id_user' => '5','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '16','id_user' => '6','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '17','id_user' => '7','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '18','id_user' => '8','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '19','id_user' => '9','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '20','id_user' => '10','created_at' => '2024-10-12 00:07:05'),
  array('id_cart' => '21','id_user' => '1','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '22','id_user' => '2','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '23','id_user' => '3','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '24','id_user' => '4','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '25','id_user' => '5','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '26','id_user' => '6','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '27','id_user' => '7','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '28','id_user' => '8','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '29','id_user' => '9','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '30','id_user' => '10','created_at' => '2024-10-12 00:10:54'),
  array('id_cart' => '31','id_user' => '1','created_at' => '2024-10-12 00:13:27'),
  array('id_cart' => '32','id_user' => '2','created_at' => '2024-10-12 00:13:27'),
  array('id_cart' => '33','id_user' => '3','created_at' => '2024-10-12 00:13:27'),
  array('id_cart' => '34','id_user' => '4','created_at' => '2024-10-12 00:13:27'),
  array('id_cart' => '35','id_user' => '5','created_at' => '2024-10-12 00:13:27'),
  array('id_cart' => '36','id_user' => '6','created_at' => '2024-10-12 00:13:27'),
  array('id_cart' => '37','id_user' => '7','created_at' => '2024-10-12 00:13:27'),
  array('id_cart' => '38','id_user' => '8','created_at' => '2024-10-12 00:13:27'),
  array('id_cart' => '39','id_user' => '9','created_at' => '2024-10-12 00:13:27'),
  array('id_cart' => '40','id_user' => '10','created_at' => '2024-10-12 00:13:27')
);

/* `e-commerce-sql`.`cart_product` */
$cart_product = array(
  array('id_cart_product' => '1','id_cart' => '1','id_product' => '12','quantity' => '1'),
  array('id_cart_product' => '2','id_cart' => '1','id_product' => '11','quantity' => '3'),
  array('id_cart_product' => '3','id_cart' => '1','id_product' => '11','quantity' => '2'),
  array('id_cart_product' => '4','id_cart' => '2','id_product' => '7','quantity' => '3'),
  array('id_cart_product' => '5','id_cart' => '2','id_product' => '5','quantity' => '1'),
  array('id_cart_product' => '6','id_cart' => '2','id_product' => '8','quantity' => '4'),
  array('id_cart_product' => '7','id_cart' => '3','id_product' => '18','quantity' => '3'),
  array('id_cart_product' => '8','id_cart' => '3','id_product' => '14','quantity' => '1'),
  array('id_cart_product' => '9','id_cart' => '3','id_product' => '2','quantity' => '5'),
  array('id_cart_product' => '10','id_cart' => '4','id_product' => '6','quantity' => '5'),
  array('id_cart_product' => '11','id_cart' => '4','id_product' => '4','quantity' => '1'),
  array('id_cart_product' => '12','id_cart' => '4','id_product' => '18','quantity' => '1'),
  array('id_cart_product' => '13','id_cart' => '5','id_product' => '6','quantity' => '2'),
  array('id_cart_product' => '14','id_cart' => '5','id_product' => '1','quantity' => '2'),
  array('id_cart_product' => '15','id_cart' => '5','id_product' => '3','quantity' => '3'),
  array('id_cart_product' => '16','id_cart' => '6','id_product' => '19','quantity' => '3'),
  array('id_cart_product' => '17','id_cart' => '6','id_product' => '15','quantity' => '1'),
  array('id_cart_product' => '18','id_cart' => '6','id_product' => '11','quantity' => '3'),
  array('id_cart_product' => '19','id_cart' => '7','id_product' => '6','quantity' => '1'),
  array('id_cart_product' => '20','id_cart' => '7','id_product' => '17','quantity' => '4'),
  array('id_cart_product' => '21','id_cart' => '7','id_product' => '20','quantity' => '4'),
  array('id_cart_product' => '22','id_cart' => '8','id_product' => '1','quantity' => '5'),
  array('id_cart_product' => '23','id_cart' => '8','id_product' => '6','quantity' => '5'),
  array('id_cart_product' => '24','id_cart' => '8','id_product' => '4','quantity' => '5'),
  array('id_cart_product' => '25','id_cart' => '9','id_product' => '8','quantity' => '2'),
  array('id_cart_product' => '26','id_cart' => '9','id_product' => '15','quantity' => '5'),
  array('id_cart_product' => '27','id_cart' => '9','id_product' => '14','quantity' => '5'),
  array('id_cart_product' => '28','id_cart' => '10','id_product' => '5','quantity' => '5'),
  array('id_cart_product' => '29','id_cart' => '10','id_product' => '9','quantity' => '5'),
  array('id_cart_product' => '30','id_cart' => '10','id_product' => '17','quantity' => '5'),
  array('id_cart_product' => '31','id_cart' => '1','id_product' => '10','quantity' => '4'),
  array('id_cart_product' => '32','id_cart' => '1','id_product' => '7','quantity' => '2'),
  array('id_cart_product' => '33','id_cart' => '1','id_product' => '12','quantity' => '3'),
  array('id_cart_product' => '34','id_cart' => '2','id_product' => '11','quantity' => '3'),
  array('id_cart_product' => '35','id_cart' => '2','id_product' => '18','quantity' => '5'),
  array('id_cart_product' => '36','id_cart' => '2','id_product' => '9','quantity' => '5'),
  array('id_cart_product' => '37','id_cart' => '3','id_product' => '3','quantity' => '5'),
  array('id_cart_product' => '38','id_cart' => '3','id_product' => '8','quantity' => '3'),
  array('id_cart_product' => '39','id_cart' => '3','id_product' => '17','quantity' => '4'),
  array('id_cart_product' => '40','id_cart' => '4','id_product' => '9','quantity' => '5'),
  array('id_cart_product' => '41','id_cart' => '4','id_product' => '12','quantity' => '3'),
  array('id_cart_product' => '42','id_cart' => '4','id_product' => '20','quantity' => '3'),
  array('id_cart_product' => '43','id_cart' => '5','id_product' => '3','quantity' => '1'),
  array('id_cart_product' => '44','id_cart' => '5','id_product' => '4','quantity' => '3'),
  array('id_cart_product' => '45','id_cart' => '5','id_product' => '9','quantity' => '4'),
  array('id_cart_product' => '46','id_cart' => '6','id_product' => '11','quantity' => '2'),
  array('id_cart_product' => '47','id_cart' => '6','id_product' => '18','quantity' => '1'),
  array('id_cart_product' => '48','id_cart' => '6','id_product' => '6','quantity' => '3'),
  array('id_cart_product' => '49','id_cart' => '7','id_product' => '9','quantity' => '1'),
  array('id_cart_product' => '50','id_cart' => '7','id_product' => '10','quantity' => '1'),
  array('id_cart_product' => '51','id_cart' => '7','id_product' => '9','quantity' => '4'),
  array('id_cart_product' => '52','id_cart' => '8','id_product' => '11','quantity' => '1'),
  array('id_cart_product' => '53','id_cart' => '8','id_product' => '14','quantity' => '5'),
  array('id_cart_product' => '54','id_cart' => '8','id_product' => '16','quantity' => '3'),
  array('id_cart_product' => '55','id_cart' => '9','id_product' => '6','quantity' => '4'),
  array('id_cart_product' => '56','id_cart' => '9','id_product' => '19','quantity' => '4'),
  array('id_cart_product' => '57','id_cart' => '9','id_product' => '6','quantity' => '3'),
  array('id_cart_product' => '58','id_cart' => '10','id_product' => '12','quantity' => '5'),
  array('id_cart_product' => '59','id_cart' => '10','id_product' => '20','quantity' => '5'),
  array('id_cart_product' => '60','id_cart' => '10','id_product' => '15','quantity' => '4'),
  array('id_cart_product' => '61','id_cart' => '1','id_product' => '6','quantity' => '2'),
  array('id_cart_product' => '62','id_cart' => '1','id_product' => '6','quantity' => '1'),
  array('id_cart_product' => '63','id_cart' => '1','id_product' => '19','quantity' => '1'),
  array('id_cart_product' => '64','id_cart' => '2','id_product' => '18','quantity' => '4'),
  array('id_cart_product' => '65','id_cart' => '2','id_product' => '9','quantity' => '1'),
  array('id_cart_product' => '66','id_cart' => '2','id_product' => '7','quantity' => '5'),
  array('id_cart_product' => '67','id_cart' => '3','id_product' => '12','quantity' => '3'),
  array('id_cart_product' => '68','id_cart' => '3','id_product' => '3','quantity' => '1'),
  array('id_cart_product' => '69','id_cart' => '3','id_product' => '15','quantity' => '2'),
  array('id_cart_product' => '70','id_cart' => '4','id_product' => '9','quantity' => '4'),
  array('id_cart_product' => '71','id_cart' => '4','id_product' => '16','quantity' => '3'),
  array('id_cart_product' => '72','id_cart' => '4','id_product' => '9','quantity' => '3'),
  array('id_cart_product' => '73','id_cart' => '5','id_product' => '2','quantity' => '5'),
  array('id_cart_product' => '74','id_cart' => '5','id_product' => '14','quantity' => '4'),
  array('id_cart_product' => '75','id_cart' => '5','id_product' => '7','quantity' => '2'),
  array('id_cart_product' => '76','id_cart' => '6','id_product' => '10','quantity' => '1'),
  array('id_cart_product' => '77','id_cart' => '6','id_product' => '17','quantity' => '5'),
  array('id_cart_product' => '78','id_cart' => '6','id_product' => '14','quantity' => '1'),
  array('id_cart_product' => '79','id_cart' => '7','id_product' => '19','quantity' => '3'),
  array('id_cart_product' => '80','id_cart' => '7','id_product' => '2','quantity' => '3'),
  array('id_cart_product' => '81','id_cart' => '7','id_product' => '7','quantity' => '2'),
  array('id_cart_product' => '82','id_cart' => '8','id_product' => '11','quantity' => '3'),
  array('id_cart_product' => '83','id_cart' => '8','id_product' => '9','quantity' => '1'),
  array('id_cart_product' => '84','id_cart' => '8','id_product' => '10','quantity' => '3'),
  array('id_cart_product' => '85','id_cart' => '9','id_product' => '2','quantity' => '1'),
  array('id_cart_product' => '86','id_cart' => '9','id_product' => '13','quantity' => '5'),
  array('id_cart_product' => '87','id_cart' => '9','id_product' => '13','quantity' => '4'),
  array('id_cart_product' => '88','id_cart' => '10','id_product' => '1','quantity' => '4'),
  array('id_cart_product' => '89','id_cart' => '10','id_product' => '4','quantity' => '4'),
  array('id_cart_product' => '90','id_cart' => '10','id_product' => '9','quantity' => '5'),
  array('id_cart_product' => '91','id_cart' => '1','id_product' => '9','quantity' => '3'),
  array('id_cart_product' => '92','id_cart' => '1','id_product' => '14','quantity' => '5'),
  array('id_cart_product' => '93','id_cart' => '1','id_product' => '16','quantity' => '2'),
  array('id_cart_product' => '94','id_cart' => '2','id_product' => '20','quantity' => '1'),
  array('id_cart_product' => '95','id_cart' => '2','id_product' => '12','quantity' => '2'),
  array('id_cart_product' => '96','id_cart' => '2','id_product' => '12','quantity' => '5'),
  array('id_cart_product' => '97','id_cart' => '3','id_product' => '4','quantity' => '4'),
  array('id_cart_product' => '98','id_cart' => '3','id_product' => '17','quantity' => '1'),
  array('id_cart_product' => '99','id_cart' => '3','id_product' => '3','quantity' => '2'),
  array('id_cart_product' => '100','id_cart' => '4','id_product' => '1','quantity' => '1'),
  array('id_cart_product' => '101','id_cart' => '4','id_product' => '5','quantity' => '3'),
  array('id_cart_product' => '102','id_cart' => '4','id_product' => '14','quantity' => '2'),
  array('id_cart_product' => '103','id_cart' => '5','id_product' => '11','quantity' => '1'),
  array('id_cart_product' => '104','id_cart' => '5','id_product' => '6','quantity' => '4'),
  array('id_cart_product' => '105','id_cart' => '5','id_product' => '14','quantity' => '4'),
  array('id_cart_product' => '106','id_cart' => '6','id_product' => '15','quantity' => '5'),
  array('id_cart_product' => '107','id_cart' => '6','id_product' => '16','quantity' => '4'),
  array('id_cart_product' => '108','id_cart' => '6','id_product' => '20','quantity' => '4'),
  array('id_cart_product' => '109','id_cart' => '7','id_product' => '7','quantity' => '2'),
  array('id_cart_product' => '110','id_cart' => '7','id_product' => '2','quantity' => '2'),
  array('id_cart_product' => '111','id_cart' => '7','id_product' => '6','quantity' => '1'),
  array('id_cart_product' => '112','id_cart' => '8','id_product' => '7','quantity' => '4'),
  array('id_cart_product' => '113','id_cart' => '8','id_product' => '5','quantity' => '1'),
  array('id_cart_product' => '114','id_cart' => '8','id_product' => '20','quantity' => '2'),
  array('id_cart_product' => '115','id_cart' => '9','id_product' => '1','quantity' => '5'),
  array('id_cart_product' => '116','id_cart' => '9','id_product' => '14','quantity' => '5'),
  array('id_cart_product' => '117','id_cart' => '9','id_product' => '11','quantity' => '4'),
  array('id_cart_product' => '118','id_cart' => '10','id_product' => '17','quantity' => '1'),
  array('id_cart_product' => '119','id_cart' => '10','id_product' => '16','quantity' => '1'),
  array('id_cart_product' => '120','id_cart' => '10','id_product' => '18','quantity' => '5')
);

/* `e-commerce-sql`.`command` */
$command = array(
  array('id_command' => '1','id_user' => '1','id_address' => '1','total_price' => '49.95','status' => 'shipped','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '2','id_user' => '2','id_address' => '2','total_price' => '15.33','status' => 'shipped','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '3','id_user' => '3','id_address' => '3','total_price' => '39.63','status' => 'shipped','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '4','id_user' => '4','id_address' => '4','total_price' => '139.97','status' => 'shipped','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '5','id_user' => '5','id_address' => '5','total_price' => '193.44','status' => 'delivered','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '6','id_user' => '6','id_address' => '6','total_price' => '147.85','status' => 'shipped','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '7','id_user' => '7','id_address' => '7','total_price' => '110.02','status' => 'pending','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '8','id_user' => '8','id_address' => '8','total_price' => '132.91','status' => 'shipped','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '9','id_user' => '9','id_address' => '9','total_price' => '148.11','status' => 'shipped','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '10','id_user' => '10','id_address' => '10','total_price' => '111.94','status' => 'delivered','created_at' => '2024-10-12 00:02:30'),
  array('id_command' => '11','id_user' => '1','id_address' => '1','total_price' => '72.03','status' => 'shipped','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '12','id_user' => '2','id_address' => '2','total_price' => '176.15','status' => 'delivered','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '13','id_user' => '3','id_address' => '3','total_price' => '112.12','status' => 'delivered','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '14','id_user' => '4','id_address' => '4','total_price' => '27.43','status' => 'pending','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '15','id_user' => '5','id_address' => '5','total_price' => '99.90','status' => 'delivered','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '16','id_user' => '6','id_address' => '6','total_price' => '41.73','status' => 'delivered','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '17','id_user' => '7','id_address' => '7','total_price' => '141.84','status' => 'delivered','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '18','id_user' => '8','id_address' => '8','total_price' => '93.23','status' => 'pending','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '19','id_user' => '9','id_address' => '9','total_price' => '38.50','status' => 'pending','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '20','id_user' => '10','id_address' => '10','total_price' => '163.15','status' => 'delivered','created_at' => '2024-10-12 00:07:05'),
  array('id_command' => '21','id_user' => '1','id_address' => '1','total_price' => '41.72','status' => 'delivered','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '22','id_user' => '2','id_address' => '2','total_price' => '173.69','status' => 'pending','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '23','id_user' => '3','id_address' => '3','total_price' => '33.45','status' => 'pending','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '24','id_user' => '4','id_address' => '4','total_price' => '151.91','status' => 'pending','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '25','id_user' => '5','id_address' => '5','total_price' => '21.93','status' => 'shipped','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '26','id_user' => '6','id_address' => '6','total_price' => '171.94','status' => 'pending','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '27','id_user' => '7','id_address' => '7','total_price' => '121.69','status' => 'pending','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '28','id_user' => '8','id_address' => '8','total_price' => '69.23','status' => 'shipped','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '29','id_user' => '9','id_address' => '9','total_price' => '149.67','status' => 'shipped','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '30','id_user' => '10','id_address' => '10','total_price' => '58.14','status' => 'shipped','created_at' => '2024-10-12 00:10:54'),
  array('id_command' => '31','id_user' => '1','id_address' => '1','total_price' => '137.69','status' => 'shipped','created_at' => '2024-10-12 00:13:27'),
  array('id_command' => '32','id_user' => '2','id_address' => '2','total_price' => '160.12','status' => 'shipped','created_at' => '2024-10-12 00:13:27'),
  array('id_command' => '33','id_user' => '3','id_address' => '3','total_price' => '18.96','status' => 'pending','created_at' => '2024-10-12 00:13:27'),
  array('id_command' => '34','id_user' => '4','id_address' => '4','total_price' => '161.36','status' => 'shipped','created_at' => '2024-10-12 00:13:27'),
  array('id_command' => '35','id_user' => '5','id_address' => '5','total_price' => '49.19','status' => 'pending','created_at' => '2024-10-12 00:13:27'),
  array('id_command' => '36','id_user' => '6','id_address' => '6','total_price' => '141.22','status' => 'pending','created_at' => '2024-10-12 00:13:27'),
  array('id_command' => '37','id_user' => '7','id_address' => '7','total_price' => '21.35','status' => 'shipped','created_at' => '2024-10-12 00:13:27'),
  array('id_command' => '38','id_user' => '8','id_address' => '8','total_price' => '140.57','status' => 'delivered','created_at' => '2024-10-12 00:13:27'),
  array('id_command' => '39','id_user' => '9','id_address' => '9','total_price' => '129.95','status' => 'shipped','created_at' => '2024-10-12 00:13:27'),
  array('id_command' => '40','id_user' => '10','id_address' => '10','total_price' => '57.38','status' => 'shipped','created_at' => '2024-10-12 00:13:27')
);

/* `e-commerce-sql`.`command_product` */
$command_product = array(
  array('id_command_product' => '1','id_command' => '1','id_product' => '8','quantity' => '5'),
  array('id_command_product' => '2','id_command' => '1','id_product' => '11','quantity' => '2'),
  array('id_command_product' => '3','id_command' => '1','id_product' => '7','quantity' => '2'),
  array('id_command_product' => '4','id_command' => '2','id_product' => '20','quantity' => '2'),
  array('id_command_product' => '5','id_command' => '2','id_product' => '12','quantity' => '5'),
  array('id_command_product' => '6','id_command' => '2','id_product' => '11','quantity' => '1'),
  array('id_command_product' => '7','id_command' => '3','id_product' => '8','quantity' => '2'),
  array('id_command_product' => '8','id_command' => '3','id_product' => '15','quantity' => '5'),
  array('id_command_product' => '9','id_command' => '3','id_product' => '18','quantity' => '5'),
  array('id_command_product' => '10','id_command' => '4','id_product' => '4','quantity' => '3'),
  array('id_command_product' => '11','id_command' => '4','id_product' => '14','quantity' => '5'),
  array('id_command_product' => '12','id_command' => '4','id_product' => '5','quantity' => '3'),
  array('id_command_product' => '13','id_command' => '5','id_product' => '7','quantity' => '1'),
  array('id_command_product' => '14','id_command' => '5','id_product' => '11','quantity' => '1'),
  array('id_command_product' => '15','id_command' => '5','id_product' => '14','quantity' => '2'),
  array('id_command_product' => '16','id_command' => '6','id_product' => '8','quantity' => '4'),
  array('id_command_product' => '17','id_command' => '6','id_product' => '7','quantity' => '2'),
  array('id_command_product' => '18','id_command' => '6','id_product' => '3','quantity' => '2'),
  array('id_command_product' => '19','id_command' => '7','id_product' => '7','quantity' => '3'),
  array('id_command_product' => '20','id_command' => '7','id_product' => '7','quantity' => '5'),
  array('id_command_product' => '21','id_command' => '7','id_product' => '3','quantity' => '4'),
  array('id_command_product' => '22','id_command' => '8','id_product' => '14','quantity' => '2'),
  array('id_command_product' => '23','id_command' => '8','id_product' => '9','quantity' => '4'),
  array('id_command_product' => '24','id_command' => '8','id_product' => '3','quantity' => '3'),
  array('id_command_product' => '25','id_command' => '9','id_product' => '10','quantity' => '2'),
  array('id_command_product' => '26','id_command' => '9','id_product' => '6','quantity' => '5'),
  array('id_command_product' => '27','id_command' => '9','id_product' => '13','quantity' => '1'),
  array('id_command_product' => '28','id_command' => '10','id_product' => '6','quantity' => '5'),
  array('id_command_product' => '29','id_command' => '10','id_product' => '12','quantity' => '3'),
  array('id_command_product' => '30','id_command' => '10','id_product' => '4','quantity' => '3'),
  array('id_command_product' => '31','id_command' => '1','id_product' => '11','quantity' => '2'),
  array('id_command_product' => '32','id_command' => '1','id_product' => '5','quantity' => '3'),
  array('id_command_product' => '33','id_command' => '1','id_product' => '11','quantity' => '3'),
  array('id_command_product' => '34','id_command' => '2','id_product' => '2','quantity' => '1'),
  array('id_command_product' => '35','id_command' => '2','id_product' => '3','quantity' => '3'),
  array('id_command_product' => '36','id_command' => '2','id_product' => '20','quantity' => '4'),
  array('id_command_product' => '37','id_command' => '3','id_product' => '6','quantity' => '2'),
  array('id_command_product' => '38','id_command' => '3','id_product' => '12','quantity' => '4'),
  array('id_command_product' => '39','id_command' => '3','id_product' => '9','quantity' => '4'),
  array('id_command_product' => '40','id_command' => '4','id_product' => '6','quantity' => '3'),
  array('id_command_product' => '41','id_command' => '4','id_product' => '8','quantity' => '4'),
  array('id_command_product' => '42','id_command' => '4','id_product' => '13','quantity' => '1'),
  array('id_command_product' => '43','id_command' => '5','id_product' => '4','quantity' => '2'),
  array('id_command_product' => '44','id_command' => '5','id_product' => '18','quantity' => '4'),
  array('id_command_product' => '45','id_command' => '5','id_product' => '15','quantity' => '4'),
  array('id_command_product' => '46','id_command' => '6','id_product' => '14','quantity' => '5'),
  array('id_command_product' => '47','id_command' => '6','id_product' => '16','quantity' => '1'),
  array('id_command_product' => '48','id_command' => '6','id_product' => '1','quantity' => '1'),
  array('id_command_product' => '49','id_command' => '7','id_product' => '4','quantity' => '5'),
  array('id_command_product' => '50','id_command' => '7','id_product' => '11','quantity' => '3'),
  array('id_command_product' => '51','id_command' => '7','id_product' => '12','quantity' => '5'),
  array('id_command_product' => '52','id_command' => '8','id_product' => '2','quantity' => '2'),
  array('id_command_product' => '53','id_command' => '8','id_product' => '4','quantity' => '5'),
  array('id_command_product' => '54','id_command' => '8','id_product' => '4','quantity' => '2'),
  array('id_command_product' => '55','id_command' => '9','id_product' => '6','quantity' => '2'),
  array('id_command_product' => '56','id_command' => '9','id_product' => '20','quantity' => '4'),
  array('id_command_product' => '57','id_command' => '9','id_product' => '8','quantity' => '2'),
  array('id_command_product' => '58','id_command' => '10','id_product' => '8','quantity' => '3'),
  array('id_command_product' => '59','id_command' => '10','id_product' => '7','quantity' => '5'),
  array('id_command_product' => '60','id_command' => '10','id_product' => '4','quantity' => '4'),
  array('id_command_product' => '61','id_command' => '1','id_product' => '9','quantity' => '2'),
  array('id_command_product' => '62','id_command' => '1','id_product' => '4','quantity' => '2'),
  array('id_command_product' => '63','id_command' => '1','id_product' => '7','quantity' => '1'),
  array('id_command_product' => '64','id_command' => '2','id_product' => '3','quantity' => '2'),
  array('id_command_product' => '65','id_command' => '2','id_product' => '3','quantity' => '5'),
  array('id_command_product' => '66','id_command' => '2','id_product' => '18','quantity' => '4'),
  array('id_command_product' => '67','id_command' => '3','id_product' => '4','quantity' => '3'),
  array('id_command_product' => '68','id_command' => '3','id_product' => '3','quantity' => '1'),
  array('id_command_product' => '69','id_command' => '3','id_product' => '12','quantity' => '1'),
  array('id_command_product' => '70','id_command' => '4','id_product' => '10','quantity' => '1'),
  array('id_command_product' => '71','id_command' => '4','id_product' => '14','quantity' => '3'),
  array('id_command_product' => '72','id_command' => '4','id_product' => '12','quantity' => '3'),
  array('id_command_product' => '73','id_command' => '5','id_product' => '18','quantity' => '1'),
  array('id_command_product' => '74','id_command' => '5','id_product' => '15','quantity' => '1'),
  array('id_command_product' => '75','id_command' => '5','id_product' => '4','quantity' => '4'),
  array('id_command_product' => '76','id_command' => '6','id_product' => '6','quantity' => '1'),
  array('id_command_product' => '77','id_command' => '6','id_product' => '14','quantity' => '5'),
  array('id_command_product' => '78','id_command' => '6','id_product' => '19','quantity' => '5'),
  array('id_command_product' => '79','id_command' => '7','id_product' => '16','quantity' => '1'),
  array('id_command_product' => '80','id_command' => '7','id_product' => '13','quantity' => '1'),
  array('id_command_product' => '81','id_command' => '7','id_product' => '15','quantity' => '2'),
  array('id_command_product' => '82','id_command' => '8','id_product' => '4','quantity' => '3'),
  array('id_command_product' => '83','id_command' => '8','id_product' => '14','quantity' => '1'),
  array('id_command_product' => '84','id_command' => '8','id_product' => '15','quantity' => '3'),
  array('id_command_product' => '85','id_command' => '9','id_product' => '11','quantity' => '3'),
  array('id_command_product' => '86','id_command' => '9','id_product' => '19','quantity' => '4'),
  array('id_command_product' => '87','id_command' => '9','id_product' => '6','quantity' => '4'),
  array('id_command_product' => '88','id_command' => '10','id_product' => '4','quantity' => '2'),
  array('id_command_product' => '89','id_command' => '10','id_product' => '19','quantity' => '5'),
  array('id_command_product' => '90','id_command' => '10','id_product' => '5','quantity' => '4'),
  array('id_command_product' => '91','id_command' => '1','id_product' => '6','quantity' => '5'),
  array('id_command_product' => '92','id_command' => '1','id_product' => '17','quantity' => '4'),
  array('id_command_product' => '93','id_command' => '1','id_product' => '2','quantity' => '3'),
  array('id_command_product' => '94','id_command' => '2','id_product' => '16','quantity' => '1'),
  array('id_command_product' => '95','id_command' => '2','id_product' => '5','quantity' => '2'),
  array('id_command_product' => '96','id_command' => '2','id_product' => '4','quantity' => '1'),
  array('id_command_product' => '97','id_command' => '3','id_product' => '18','quantity' => '2'),
  array('id_command_product' => '98','id_command' => '3','id_product' => '12','quantity' => '1'),
  array('id_command_product' => '99','id_command' => '3','id_product' => '6','quantity' => '4'),
  array('id_command_product' => '100','id_command' => '4','id_product' => '15','quantity' => '2'),
  array('id_command_product' => '101','id_command' => '4','id_product' => '6','quantity' => '3'),
  array('id_command_product' => '102','id_command' => '4','id_product' => '13','quantity' => '3'),
  array('id_command_product' => '103','id_command' => '5','id_product' => '3','quantity' => '2'),
  array('id_command_product' => '104','id_command' => '5','id_product' => '12','quantity' => '3'),
  array('id_command_product' => '105','id_command' => '5','id_product' => '15','quantity' => '2'),
  array('id_command_product' => '106','id_command' => '6','id_product' => '7','quantity' => '1'),
  array('id_command_product' => '107','id_command' => '6','id_product' => '8','quantity' => '2'),
  array('id_command_product' => '108','id_command' => '6','id_product' => '19','quantity' => '1'),
  array('id_command_product' => '109','id_command' => '7','id_product' => '10','quantity' => '2'),
  array('id_command_product' => '110','id_command' => '7','id_product' => '1','quantity' => '3'),
  array('id_command_product' => '111','id_command' => '7','id_product' => '7','quantity' => '2'),
  array('id_command_product' => '112','id_command' => '8','id_product' => '1','quantity' => '5'),
  array('id_command_product' => '113','id_command' => '8','id_product' => '17','quantity' => '4'),
  array('id_command_product' => '114','id_command' => '8','id_product' => '17','quantity' => '2'),
  array('id_command_product' => '115','id_command' => '9','id_product' => '11','quantity' => '5'),
  array('id_command_product' => '116','id_command' => '9','id_product' => '1','quantity' => '4'),
  array('id_command_product' => '117','id_command' => '9','id_product' => '13','quantity' => '5'),
  array('id_command_product' => '118','id_command' => '10','id_product' => '14','quantity' => '5'),
  array('id_command_product' => '119','id_command' => '10','id_product' => '3','quantity' => '4'),
  array('id_command_product' => '120','id_command' => '10','id_product' => '17','quantity' => '3')
);

/* `e-commerce-sql`.`invoice` */
$invoice = array(
  array('id_invoice' => '1','id_command' => '1','invoice_date' => '2024-09-23 00:21:51','total_price' => '78.03','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '2','id_command' => '2','invoice_date' => '2024-09-22 07:39:09','total_price' => '113.98','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '3','id_command' => '3','invoice_date' => '2024-09-19 06:48:18','total_price' => '115.96','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '4','id_command' => '4','invoice_date' => '2024-09-29 01:43:54','total_price' => '107.40','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '5','id_command' => '5','invoice_date' => '2024-10-01 11:34:01','total_price' => '101.56','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '6','id_command' => '6','invoice_date' => '2024-09-15 19:24:46','total_price' => '44.85','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '7','id_command' => '7','invoice_date' => '2024-10-10 20:22:42','total_price' => '123.94','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '8','id_command' => '8','invoice_date' => '2024-09-16 16:56:05','total_price' => '43.66','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '9','id_command' => '9','invoice_date' => '2024-10-08 18:41:20','total_price' => '85.13','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '10','id_command' => '10','invoice_date' => '2024-09-30 23:52:37','total_price' => '92.61','created_at' => '2024-10-12 00:02:30'),
  array('id_invoice' => '11','id_command' => '1','invoice_date' => '2024-09-12 01:04:27','total_price' => '148.88','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '12','id_command' => '2','invoice_date' => '2024-10-08 19:58:52','total_price' => '20.34','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '13','id_command' => '3','invoice_date' => '2024-09-30 20:44:04','total_price' => '168.52','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '14','id_command' => '4','invoice_date' => '2024-10-01 13:05:56','total_price' => '152.07','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '15','id_command' => '5','invoice_date' => '2024-10-11 14:13:29','total_price' => '97.51','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '16','id_command' => '6','invoice_date' => '2024-10-06 08:11:46','total_price' => '101.91','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '17','id_command' => '7','invoice_date' => '2024-09-22 06:49:39','total_price' => '34.27','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '18','id_command' => '8','invoice_date' => '2024-10-06 06:41:20','total_price' => '52.26','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '19','id_command' => '9','invoice_date' => '2024-09-21 03:10:33','total_price' => '110.15','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '20','id_command' => '10','invoice_date' => '2024-09-30 10:27:31','total_price' => '24.87','created_at' => '2024-10-12 00:07:05'),
  array('id_invoice' => '21','id_command' => '1','invoice_date' => '2024-09-16 13:37:07','total_price' => '196.51','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '22','id_command' => '2','invoice_date' => '2024-10-03 12:32:04','total_price' => '131.81','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '23','id_command' => '3','invoice_date' => '2024-10-02 07:29:17','total_price' => '122.83','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '24','id_command' => '4','invoice_date' => '2024-09-16 16:39:06','total_price' => '113.52','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '25','id_command' => '5','invoice_date' => '2024-09-21 14:53:49','total_price' => '109.63','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '26','id_command' => '6','invoice_date' => '2024-10-01 19:09:43','total_price' => '155.52','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '27','id_command' => '7','invoice_date' => '2024-09-17 13:20:36','total_price' => '175.50','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '28','id_command' => '8','invoice_date' => '2024-09-12 03:22:25','total_price' => '164.45','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '29','id_command' => '9','invoice_date' => '2024-09-16 03:00:38','total_price' => '120.58','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '30','id_command' => '10','invoice_date' => '2024-09-26 18:42:32','total_price' => '68.94','created_at' => '2024-10-12 00:10:54'),
  array('id_invoice' => '31','id_command' => '1','invoice_date' => '2024-09-27 19:03:35','total_price' => '58.65','created_at' => '2024-10-12 00:13:27'),
  array('id_invoice' => '32','id_command' => '2','invoice_date' => '2024-10-07 21:06:41','total_price' => '70.66','created_at' => '2024-10-12 00:13:27'),
  array('id_invoice' => '33','id_command' => '3','invoice_date' => '2024-09-15 00:39:33','total_price' => '127.01','created_at' => '2024-10-12 00:13:27'),
  array('id_invoice' => '34','id_command' => '4','invoice_date' => '2024-09-27 12:53:56','total_price' => '115.49','created_at' => '2024-10-12 00:13:27'),
  array('id_invoice' => '35','id_command' => '5','invoice_date' => '2024-09-30 06:22:45','total_price' => '66.33','created_at' => '2024-10-12 00:13:27'),
  array('id_invoice' => '36','id_command' => '6','invoice_date' => '2024-10-10 08:27:02','total_price' => '181.23','created_at' => '2024-10-12 00:13:27'),
  array('id_invoice' => '37','id_command' => '7','invoice_date' => '2024-09-23 07:20:39','total_price' => '41.33','created_at' => '2024-10-12 00:13:27'),
  array('id_invoice' => '38','id_command' => '8','invoice_date' => '2024-09-15 10:03:40','total_price' => '153.92','created_at' => '2024-10-12 00:13:27'),
  array('id_invoice' => '39','id_command' => '9','invoice_date' => '2024-09-14 22:26:10','total_price' => '173.71','created_at' => '2024-10-12 00:13:27'),
  array('id_invoice' => '40','id_command' => '10','invoice_date' => '2024-10-01 17:30:08','total_price' => '29.83','created_at' => '2024-10-12 00:13:27')
);

/* `e-commerce-sql`.`payment` */
$payment = array(
  array('id_payment' => '1','id_user' => '1','payment_type' => 'Credit Card','payment_info' => '5385414749733579'),
  array('id_payment' => '2','id_user' => '2','payment_type' => 'IBAN','payment_info' => '4916852313173'),
  array('id_payment' => '3','id_user' => '3','payment_type' => 'IBAN','payment_info' => '5289735242960427'),
  array('id_payment' => '4','id_user' => '4','payment_type' => 'IBAN','payment_info' => '4556555654956617'),
  array('id_payment' => '5','id_user' => '5','payment_type' => 'IBAN','payment_info' => '5402529888195527'),
  array('id_payment' => '6','id_user' => '6','payment_type' => 'IBAN','payment_info' => '4716531695130477'),
  array('id_payment' => '7','id_user' => '7','payment_type' => 'IBAN','payment_info' => '376261784917571'),
  array('id_payment' => '8','id_user' => '8','payment_type' => 'Credit Card','payment_info' => '6011098915241911'),
  array('id_payment' => '9','id_user' => '9','payment_type' => 'IBAN','payment_info' => '5577974114137043'),
  array('id_payment' => '10','id_user' => '10','payment_type' => 'Credit Card','payment_info' => '375347942816630')
);

/* `e-commerce-sql`.`photo` */
$photo = array(
  array('id_photo' => '1','id_user' => '8','id_product' => '1','photo_url' => 'http://lorempixel.com/640/480/products/?44843'),
  array('id_photo' => '2','id_user' => '6','id_product' => '2','photo_url' => 'http://lorempixel.com/640/480/products/?82849'),
  array('id_photo' => '3','id_user' => '3','id_product' => '3','photo_url' => 'http://lorempixel.com/640/480/products/?40099'),
  array('id_photo' => '4','id_user' => '5','id_product' => '4','photo_url' => 'http://lorempixel.com/640/480/products/?37282'),
  array('id_photo' => '5','id_user' => '7','id_product' => '5','photo_url' => 'http://lorempixel.com/640/480/products/?35431'),
  array('id_photo' => '6','id_user' => '2','id_product' => '6','photo_url' => 'http://lorempixel.com/640/480/products/?81794'),
  array('id_photo' => '7','id_user' => '3','id_product' => '7','photo_url' => 'http://lorempixel.com/640/480/products/?72395'),
  array('id_photo' => '8','id_user' => '5','id_product' => '8','photo_url' => 'http://lorempixel.com/640/480/products/?59062'),
  array('id_photo' => '9','id_user' => '4','id_product' => '9','photo_url' => 'http://lorempixel.com/640/480/products/?59244'),
  array('id_photo' => '10','id_user' => '2','id_product' => '10','photo_url' => 'http://lorempixel.com/640/480/products/?92068'),
  array('id_photo' => '11','id_user' => '6','id_product' => '11','photo_url' => 'http://lorempixel.com/640/480/products/?53997'),
  array('id_photo' => '12','id_user' => '6','id_product' => '12','photo_url' => 'http://lorempixel.com/640/480/products/?60635'),
  array('id_photo' => '13','id_user' => '1','id_product' => '13','photo_url' => 'http://lorempixel.com/640/480/products/?62344'),
  array('id_photo' => '14','id_user' => '7','id_product' => '14','photo_url' => 'http://lorempixel.com/640/480/products/?94154'),
  array('id_photo' => '15','id_user' => '6','id_product' => '15','photo_url' => 'http://lorempixel.com/640/480/products/?22940'),
  array('id_photo' => '16','id_user' => '4','id_product' => '16','photo_url' => 'http://lorempixel.com/640/480/products/?18656'),
  array('id_photo' => '17','id_user' => '7','id_product' => '17','photo_url' => 'http://lorempixel.com/640/480/products/?61762'),
  array('id_photo' => '18','id_user' => '7','id_product' => '18','photo_url' => 'http://lorempixel.com/640/480/products/?26036'),
  array('id_photo' => '19','id_user' => '5','id_product' => '19','photo_url' => 'http://lorempixel.com/640/480/products/?33136'),
  array('id_photo' => '20','id_user' => '7','id_product' => '20','photo_url' => 'http://lorempixel.com/640/480/products/?35513'),
  array('id_photo' => '21','id_user' => '5','id_product' => '1','photo_url' => 'http://lorempixel.com/640/480/products/?91975'),
  array('id_photo' => '22','id_user' => '7','id_product' => '2','photo_url' => 'http://lorempixel.com/640/480/products/?91748'),
  array('id_photo' => '23','id_user' => '9','id_product' => '3','photo_url' => 'http://lorempixel.com/640/480/products/?42261'),
  array('id_photo' => '24','id_user' => '10','id_product' => '4','photo_url' => 'http://lorempixel.com/640/480/products/?58258'),
  array('id_photo' => '25','id_user' => '2','id_product' => '5','photo_url' => 'http://lorempixel.com/640/480/products/?47941'),
  array('id_photo' => '26','id_user' => '7','id_product' => '6','photo_url' => 'http://lorempixel.com/640/480/products/?38531'),
  array('id_photo' => '27','id_user' => '2','id_product' => '7','photo_url' => 'http://lorempixel.com/640/480/products/?51975'),
  array('id_photo' => '28','id_user' => '1','id_product' => '8','photo_url' => 'http://lorempixel.com/640/480/products/?43903'),
  array('id_photo' => '29','id_user' => '3','id_product' => '9','photo_url' => 'http://lorempixel.com/640/480/products/?70657'),
  array('id_photo' => '30','id_user' => '10','id_product' => '10','photo_url' => 'http://lorempixel.com/640/480/products/?57600'),
  array('id_photo' => '31','id_user' => '1','id_product' => '11','photo_url' => 'http://lorempixel.com/640/480/products/?12463'),
  array('id_photo' => '32','id_user' => '6','id_product' => '12','photo_url' => 'http://lorempixel.com/640/480/products/?48188'),
  array('id_photo' => '33','id_user' => '4','id_product' => '13','photo_url' => 'http://lorempixel.com/640/480/products/?65137'),
  array('id_photo' => '34','id_user' => '8','id_product' => '14','photo_url' => 'http://lorempixel.com/640/480/products/?47695'),
  array('id_photo' => '35','id_user' => '2','id_product' => '15','photo_url' => 'http://lorempixel.com/640/480/products/?26144'),
  array('id_photo' => '36','id_user' => '8','id_product' => '16','photo_url' => 'http://lorempixel.com/640/480/products/?52319'),
  array('id_photo' => '37','id_user' => '10','id_product' => '17','photo_url' => 'http://lorempixel.com/640/480/products/?20750'),
  array('id_photo' => '38','id_user' => '4','id_product' => '18','photo_url' => 'http://lorempixel.com/640/480/products/?42160'),
  array('id_photo' => '39','id_user' => '3','id_product' => '19','photo_url' => 'http://lorempixel.com/640/480/products/?97218'),
  array('id_photo' => '40','id_user' => '6','id_product' => '20','photo_url' => 'http://lorempixel.com/640/480/products/?57846')
);

/* `e-commerce-sql`.`product` */
$product = array(
  array('id_product' => '1','name' => 'voluptatem','description' => 'Odit labore et omnis eligendi et. Necessitatibus est sed tenetur eum explicabo.','price' => '11.42','stock_quantity' => '25'),
  array('id_product' => '2','name' => 'sed','description' => 'Sed ab aut corporis neque odio. Nesciunt repellat odio beatae aut. Consequatur autem et dolor libero.','price' => '23.95','stock_quantity' => '28'),
  array('id_product' => '3','name' => 'illo','description' => 'Vel quidem ipsa aut quis aperiam dignissimos. Nam quia est facilis nulla dicta. Ducimus illo quidem ea voluptates.','price' => '91.62','stock_quantity' => '19'),
  array('id_product' => '4','name' => 'porro','description' => 'Et facere aut non odio harum qui repudiandae. Possimus dolores voluptatem amet consequatur magni qui. Iusto commodi voluptatem sit ad animi.','price' => '54.22','stock_quantity' => '3'),
  array('id_product' => '5','name' => 'nam','description' => 'Possimus vel sequi sed provident quia placeat iure. In minima similique consequatur sit et. Quasi voluptate id quo odit et. Molestias fuga quibusdam tempore et.','price' => '22.90','stock_quantity' => '9'),
  array('id_product' => '6','name' => 'quisquam','description' => 'Harum nesciunt aut ut cum laborum. Aut autem eum labore quo expedita. Beatae voluptas explicabo sequi non sint facere voluptatem. Nesciunt id debitis voluptas perspiciatis.','price' => '52.79','stock_quantity' => '22'),
  array('id_product' => '7','name' => 'ea','description' => 'Officiis cum molestias ab quidem sint nulla. Itaque delectus et accusantium consequatur. Voluptatibus facere est aliquam saepe.','price' => '99.85','stock_quantity' => '24'),
  array('id_product' => '8','name' => 'excepturi','description' => 'Quia ea inventore numquam commodi hic dolor. Tempore debitis et quasi ut. Atque vel illo iure. Libero omnis quae illum ex doloremque.','price' => '47.17','stock_quantity' => '23'),
  array('id_product' => '9','name' => 'est','description' => 'Inventore mollitia error doloremque magnam. Rerum sequi quos assumenda ipsa eaque maxime quae. Ut quis rem quis minus incidunt consequatur aut aperiam.','price' => '8.35','stock_quantity' => '28'),
  array('id_product' => '10','name' => 'et','description' => 'Temporibus ut sequi ut doloremque sed sit. Eos quis amet non. Voluptatem illo quia architecto possimus non repudiandae omnis. Occaecati quas magnam dolor et atque sapiente reiciendis.','price' => '42.70','stock_quantity' => '48'),
  array('id_product' => '11','name' => 'architecto','description' => 'Cupiditate sit dicta sint sed. Ipsa dolor quia ipsam. Eligendi sed illo modi vel quo.','price' => '46.37','stock_quantity' => '43'),
  array('id_product' => '12','name' => 'laboriosam','description' => 'Pariatur voluptatem illo corrupti architecto in quae. Vero quia officia nostrum et est quasi id. Voluptatem possimus odio qui sapiente adipisci qui.','price' => '5.27','stock_quantity' => '34'),
  array('id_product' => '13','name' => 'voluptate','description' => 'Occaecati similique ipsam voluptatum officia amet eum. Repellat dolorem ea eum laborum qui modi dolorem. Sint qui quia voluptate quis aspernatur beatae.','price' => '64.32','stock_quantity' => '40'),
  array('id_product' => '14','name' => 'aliquid','description' => 'Ut cupiditate nulla odit. Minus quos vel suscipit accusantium alias consequatur error. Eius aut asperiores et quia architecto. Omnis dolorem accusamus est commodi illo.','price' => '4.30','stock_quantity' => '46'),
  array('id_product' => '15','name' => 'similique','description' => 'Quia doloribus dolorem sed consectetur veniam. Eum inventore consequatur quo et consequatur eius minima. Ut at aut inventore aliquam quibusdam maiores aspernatur.','price' => '96.14','stock_quantity' => '1'),
  array('id_product' => '16','name' => 'blanditiis','description' => 'Et facilis illum qui tenetur nihil. Molestiae omnis ut aut vero debitis eum. Illo dolore officia ex illum quod ex fugiat sunt. Aut officiis quia at eius sunt optio saepe.','price' => '56.55','stock_quantity' => '36'),
  array('id_product' => '17','name' => 'vitae','description' => 'Enim qui reprehenderit illo esse ad aliquam. Corporis et molestias explicabo sed commodi ea nesciunt aut. Minus et unde ducimus laborum. Rerum ad minus maxime quia ad ipsam nulla.','price' => '99.49','stock_quantity' => '29'),
  array('id_product' => '18','name' => 'sed','description' => 'Doloribus natus voluptatibus eius officiis eos voluptatem. Omnis vitae impedit labore aut provident. Maxime totam sequi occaecati accusantium eos. Minus accusamus et nam sint esse.','price' => '70.22','stock_quantity' => '34'),
  array('id_product' => '19','name' => 'autem','description' => 'Voluptatem deleniti corrupti dolorem sunt. Est natus recusandae iusto at et earum nulla. Et nihil magni consequatur quasi veritatis.','price' => '10.43','stock_quantity' => '2'),
  array('id_product' => '20','name' => 'amet','description' => 'Eligendi unde maxime incidunt odio et accusamus eligendi quam. Voluptas voluptas aut deleniti nihil recusandae eligendi dignissimos. Aliquam voluptatibus omnis qui vero dolores laudantium.','price' => '56.79','stock_quantity' => '46'),
  array('id_product' => '21','name' => 'consequuntur','description' => 'Ut architecto vitae et tenetur qui. Qui voluptatem optio doloribus dolor repellat debitis omnis. Qui aut quia maiores rerum et temporibus enim.','price' => '13.97','stock_quantity' => '7'),
  array('id_product' => '22','name' => 'officia','description' => 'Quos voluptatem ipsum aperiam consequatur et illo. Totam voluptas et nobis dolores facere sunt. Consequuntur consectetur saepe incidunt dolorem.','price' => '3.71','stock_quantity' => '8'),
  array('id_product' => '23','name' => 'magnam','description' => 'Et deserunt et ipsam. Culpa unde libero ut. Ullam aut et quasi explicabo aut.','price' => '59.93','stock_quantity' => '36'),
  array('id_product' => '24','name' => 'enim','description' => 'Voluptatem quo beatae quia in ut delectus. Maiores ipsam autem alias amet. Et enim voluptatem explicabo corrupti eveniet.','price' => '15.49','stock_quantity' => '5'),
  array('id_product' => '25','name' => 'rem','description' => 'Aut nihil assumenda voluptatem quo ut quia vel quia. Voluptas ut rerum possimus ex occaecati. Eos et dolor voluptatem officia tempore enim.','price' => '33.33','stock_quantity' => '20'),
  array('id_product' => '26','name' => 'quo','description' => 'Et expedita amet tenetur assumenda voluptas. Reprehenderit quia alias cupiditate soluta. Asperiores ad ea ducimus. Ipsam amet exercitationem vero ut ut.','price' => '30.95','stock_quantity' => '3'),
  array('id_product' => '27','name' => 'ea','description' => 'Dolorem quae quia qui nostrum quia labore. Eos minima eum repellendus aspernatur aliquid dolorem quae. Optio omnis at eaque in molestiae.','price' => '17.17','stock_quantity' => '48'),
  array('id_product' => '28','name' => 'omnis','description' => 'Similique in id perspiciatis laborum aut amet. Rem id voluptas nesciunt unde harum pariatur nihil. Aliquam sunt ut aperiam voluptas odio accusamus.','price' => '54.28','stock_quantity' => '3'),
  array('id_product' => '29','name' => 'non','description' => 'Ipsam blanditiis accusamus beatae cum. Quisquam in incidunt id voluptatem porro. Tempora repellendus ipsa neque quo eos quod et.','price' => '64.89','stock_quantity' => '6'),
  array('id_product' => '30','name' => 'quaerat','description' => 'Et eum amet recusandae maiores ea. Distinctio rerum fuga voluptatem voluptatum facilis repellendus. Sit reiciendis autem veniam est. Recusandae animi ab facere qui molestiae delectus.','price' => '88.93','stock_quantity' => '45'),
  array('id_product' => '31','name' => 'adipisci','description' => 'Molestias dicta ducimus deserunt rerum. Beatae eligendi laudantium nulla et omnis dolor. Earum accusantium aut hic itaque.','price' => '24.36','stock_quantity' => '30'),
  array('id_product' => '32','name' => 'et','description' => 'Eaque est nobis autem quia. Fuga quasi animi temporibus sit ipsa. Deserunt modi voluptas ut praesentium facilis. Dolorem voluptas consectetur eligendi qui quaerat soluta nemo.','price' => '25.84','stock_quantity' => '21'),
  array('id_product' => '33','name' => 'tempore','description' => 'Ut pariatur aperiam suscipit quo. Explicabo est incidunt natus omnis ab quis. Rem voluptates non voluptatem et a iusto omnis atque.','price' => '19.59','stock_quantity' => '4'),
  array('id_product' => '34','name' => 'nostrum','description' => 'Nulla tenetur corporis ipsam vel. Necessitatibus et eos aut nam minima a. Facere dolore illo beatae eveniet consequatur dolore.','price' => '39.36','stock_quantity' => '23'),
  array('id_product' => '35','name' => 'maxime','description' => 'Nihil perferendis pariatur excepturi voluptatem est. Provident ab quas voluptatem maxime rerum unde rem. Quaerat rerum quia voluptate excepturi in ut non.','price' => '35.75','stock_quantity' => '11'),
  array('id_product' => '36','name' => 'veritatis','description' => 'Corrupti nisi consequuntur nobis quis laudantium quam maiores dolore. Sed amet alias quaerat placeat. Consequatur rerum ratione dignissimos. Nulla quo dolorem et repudiandae natus cum molestiae.','price' => '17.47','stock_quantity' => '35'),
  array('id_product' => '37','name' => 'laborum','description' => 'Consequatur error repudiandae ipsam possimus in facere officiis. Est eius qui quasi voluptate.','price' => '28.53','stock_quantity' => '11'),
  array('id_product' => '38','name' => 'nisi','description' => 'In vel voluptate cupiditate et non. Doloribus vel aut minus dolores ex aperiam numquam. Odit dolor rem nam hic sed.','price' => '14.37','stock_quantity' => '11'),
  array('id_product' => '39','name' => 'quod','description' => 'Molestias quia quas omnis maxime amet. Quisquam alias earum est exercitationem facere nemo. Vel fugiat ad dolores provident enim.','price' => '80.88','stock_quantity' => '25'),
  array('id_product' => '40','name' => 'ea','description' => 'Eum fugiat illum sit odit ad praesentium tempora. Aut necessitatibus earum officiis dolorum nobis praesentium. Ut nulla sunt porro et velit voluptates facilis. Eum ut et temporibus numquam quae.','price' => '83.98','stock_quantity' => '15'),
  array('id_product' => '41','name' => 'odio','description' => 'Possimus debitis qui eaque nobis culpa. Molestiae quia voluptatum odio. Placeat asperiores sed facilis impedit nemo enim aliquam. Ratione sit ut aut quidem autem natus.','price' => '72.32','stock_quantity' => '3'),
  array('id_product' => '42','name' => 'suscipit','description' => 'Ea in quae dolore voluptas cupiditate. Iure pariatur et qui molestiae sit soluta molestiae odit. Et dignissimos eligendi eaque totam.','price' => '75.48','stock_quantity' => '22'),
  array('id_product' => '43','name' => 'nobis','description' => 'Neque porro et numquam illum magni. Ipsum ad optio rerum a ea. Quia amet rerum distinctio numquam.','price' => '33.15','stock_quantity' => '10'),
  array('id_product' => '44','name' => 'nihil','description' => 'Est cupiditate voluptatem magnam labore eos. Accusantium provident facilis non quidem. Quasi in et repudiandae rerum ad dolores natus. Et minima et et itaque asperiores nisi delectus.','price' => '50.65','stock_quantity' => '49'),
  array('id_product' => '45','name' => 'incidunt','description' => 'Ducimus ut voluptatibus necessitatibus atque maiores odio non accusantium. Distinctio dolorum voluptatum laborum a qui et quia. Et ut in adipisci eius enim rerum blanditiis.','price' => '20.69','stock_quantity' => '26'),
  array('id_product' => '46','name' => 'quia','description' => 'Aut quae nobis qui tenetur totam pariatur quia aut. Eum modi autem sunt veritatis vel sint. Reprehenderit corrupti modi repellat nostrum eius.','price' => '87.80','stock_quantity' => '22'),
  array('id_product' => '47','name' => 'sequi','description' => 'Maiores omnis deleniti veritatis earum et culpa necessitatibus. Assumenda iste voluptatem omnis enim illo tempore. Praesentium dolor vero unde. Quaerat provident dignissimos ipsa voluptas.','price' => '81.31','stock_quantity' => '30'),
  array('id_product' => '48','name' => 'quasi','description' => 'Veniam eius sit sit consequatur modi. Praesentium assumenda quibusdam eos nihil qui distinctio. Quo rerum sequi sequi ut.','price' => '53.95','stock_quantity' => '39'),
  array('id_product' => '49','name' => 'voluptate','description' => 'Aliquam quae ut omnis vero id explicabo neque. Enim voluptas deleniti tenetur at eos vel consequatur facilis. Doloremque assumenda ut est corrupti. Officia possimus doloremque ut nihil temporibus.','price' => '45.78','stock_quantity' => '18'),
  array('id_product' => '50','name' => 'facilis','description' => 'Saepe cum ut ut ut tempore quod. Est facilis assumenda at voluptates sint quis. Sed quo itaque distinctio sunt quae.','price' => '2.46','stock_quantity' => '7'),
  array('id_product' => '51','name' => 'et','description' => 'Ipsum ut non ab vitae saepe. Quia perferendis consequatur corporis a ea. Necessitatibus magni aliquam repudiandae.','price' => '38.47','stock_quantity' => '48'),
  array('id_product' => '52','name' => 'numquam','description' => 'Incidunt reprehenderit sunt cupiditate voluptas accusamus impedit ut. Aut recusandae sed culpa rerum est accusantium sunt. Quidem sit id aut. Natus velit voluptas eligendi adipisci et alias qui ea.','price' => '59.13','stock_quantity' => '14'),
  array('id_product' => '53','name' => 'omnis','description' => 'Deserunt occaecati libero ut mollitia qui dolore enim. Aut error dolor ut quae. Eaque quia maiores voluptatem ullam reiciendis odit vel. Quibusdam labore ipsum est reprehenderit id est.','price' => '99.25','stock_quantity' => '6'),
  array('id_product' => '54','name' => 'ipsam','description' => 'Id labore possimus in qui sit eius. Fugit debitis minus et autem recusandae. Asperiores nulla repudiandae modi quas et. Qui impedit enim voluptas quis.','price' => '14.33','stock_quantity' => '16'),
  array('id_product' => '55','name' => 'eum','description' => 'Doloremque fuga aut facilis consectetur enim eos. Et porro a laudantium ea adipisci hic.','price' => '64.63','stock_quantity' => '47'),
  array('id_product' => '56','name' => 'labore','description' => 'Reiciendis ut nulla sapiente omnis. Vel ducimus laudantium eos animi sed. Eum necessitatibus explicabo alias.','price' => '1.03','stock_quantity' => '17'),
  array('id_product' => '57','name' => 'suscipit','description' => 'Quae delectus exercitationem omnis ipsam reiciendis rerum ut magni. Est magni maiores cum ut. Perspiciatis vero repellendus quos iusto.','price' => '89.55','stock_quantity' => '20'),
  array('id_product' => '58','name' => 'et','description' => 'Impedit sed maiores est quis. Ullam corrupti voluptates molestiae et inventore temporibus consequatur. Id qui quia voluptatem qui velit.','price' => '91.32','stock_quantity' => '42'),
  array('id_product' => '59','name' => 'qui','description' => 'Voluptas molestiae sit vel labore laborum. Dolor qui non unde quae libero rem. Est voluptatum est eos eum. Aliquam laboriosam ut quia dolorem.','price' => '11.61','stock_quantity' => '46'),
  array('id_product' => '60','name' => 'error','description' => 'Tenetur rerum ut non provident iste. Ut ex et rerum laboriosam. Et modi at quia laborum.','price' => '3.96','stock_quantity' => '47'),
  array('id_product' => '61','name' => 'quae','description' => 'Illum sit illo aut ab cupiditate et laboriosam minima. Itaque maiores nemo ratione est harum dolorum. Esse quasi dolor facilis similique consequatur dignissimos asperiores.','price' => '63.26','stock_quantity' => '6'),
  array('id_product' => '62','name' => 'aliquam','description' => 'Minus quasi repellendus sint maiores autem. Suscipit enim iste qui sint quis nisi autem et. In velit neque et. Sapiente et error sit impedit deserunt libero ipsam quisquam.','price' => '38.85','stock_quantity' => '43'),
  array('id_product' => '63','name' => 'quisquam','description' => 'Saepe enim sit nam sed voluptates. Voluptatibus consequatur molestiae ab qui sed possimus. Similique quod veniam minus eum pariatur eveniet.','price' => '73.78','stock_quantity' => '29'),
  array('id_product' => '64','name' => 'adipisci','description' => 'Saepe cumque soluta unde qui voluptatem. Optio maxime voluptas in nostrum. Molestiae qui et sequi sequi modi. Consectetur suscipit quo suscipit qui voluptatem quisquam. Aut quos illum saepe.','price' => '56.15','stock_quantity' => '17'),
  array('id_product' => '65','name' => 'voluptas','description' => 'Enim voluptatibus odit qui modi. Voluptatem eveniet cumque qui nihil. Maxime perspiciatis vel quis.','price' => '12.04','stock_quantity' => '16'),
  array('id_product' => '66','name' => 'ea','description' => 'Esse optio illum rerum molestiae quia est maxime. Aperiam pariatur rem sit id. Et eum officiis id accusamus aperiam laboriosam.','price' => '49.69','stock_quantity' => '50'),
  array('id_product' => '67','name' => 'consequatur','description' => 'Molestiae eius est commodi suscipit. Ducimus eos facilis ex quo. Dolorem et est cumque aut vel praesentium nihil. Aspernatur deleniti quod quis vitae.','price' => '87.10','stock_quantity' => '25'),
  array('id_product' => '68','name' => 'quo','description' => 'Nam repudiandae consectetur aut quidem aut. Velit ut voluptas eum omnis non aut et. Omnis reprehenderit beatae suscipit sed. Quia sed quidem ut itaque nobis.','price' => '35.97','stock_quantity' => '44'),
  array('id_product' => '69','name' => 'et','description' => 'In eum id nihil et. Eius qui ratione libero. Quo alias excepturi blanditiis pariatur totam. Repellat repellat id optio impedit.','price' => '23.13','stock_quantity' => '9'),
  array('id_product' => '70','name' => 'quidem','description' => 'Vero dolores quia odit. Non nostrum architecto aut ad occaecati alias. Omnis hic consequatur delectus et. Hic beatae blanditiis minima ipsa.','price' => '59.79','stock_quantity' => '17'),
  array('id_product' => '71','name' => 'ea','description' => 'Et atque repellendus esse. Eos nobis autem eos temporibus laboriosam. Necessitatibus itaque nihil deserunt quis nisi.','price' => '99.30','stock_quantity' => '9'),
  array('id_product' => '72','name' => 'voluptas','description' => 'Occaecati unde maiores optio eius. Vitae in eius molestiae quis explicabo. Inventore commodi accusamus aut placeat et.','price' => '38.41','stock_quantity' => '26'),
  array('id_product' => '73','name' => 'qui','description' => 'Iusto quis fuga vel vel quia vel rerum. Itaque reprehenderit quas aut aliquid et in animi. Eum labore veritatis enim aperiam delectus.','price' => '52.89','stock_quantity' => '26'),
  array('id_product' => '74','name' => 'aspernatur','description' => 'Incidunt est quasi ducimus dignissimos et magnam ipsum ipsam. Odio consequuntur omnis impedit. Aperiam labore itaque omnis ipsa autem voluptates quisquam. Quis voluptas dicta molestiae excepturi.','price' => '98.62','stock_quantity' => '3'),
  array('id_product' => '75','name' => 'neque','description' => 'Commodi aliquid ducimus modi consequuntur accusantium voluptatem expedita. Asperiores occaecati sed est enim quisquam. Consequatur et dolore minima at.','price' => '39.62','stock_quantity' => '27'),
  array('id_product' => '76','name' => 'sit','description' => 'Recusandae libero sit blanditiis et eligendi nulla harum. Facere distinctio rerum voluptatem.','price' => '44.74','stock_quantity' => '50'),
  array('id_product' => '77','name' => 'modi','description' => 'Aspernatur eaque mollitia mollitia aperiam. Excepturi enim consequatur molestias consectetur possimus consequatur dolorum. Amet ex dolorem vel voluptatem adipisci.','price' => '33.33','stock_quantity' => '27'),
  array('id_product' => '78','name' => 'explicabo','description' => 'Illo deserunt delectus accusantium velit in. Ab nulla aliquid aliquam et sapiente repudiandae vel facilis. Unde praesentium ut ad eum et maxime.','price' => '20.23','stock_quantity' => '30'),
  array('id_product' => '79','name' => 'et','description' => 'Vel ipsum quo eos cupiditate fugiat ea cupiditate. Dolorum maxime quaerat et excepturi. Recusandae ut architecto aut at sit nihil.','price' => '38.44','stock_quantity' => '3'),
  array('id_product' => '80','name' => 'asperiores','description' => 'Quae eum voluptas voluptatibus animi tempora est rem. Quam neque ut possimus accusantium. Est ullam eveniet fugit.
Maiores cum perferendis aut est quod odit impedit. Sint aspernatur modi iste.','price' => '67.55','stock_quantity' => '23')
);

/* `e-commerce-sql`.`rate` */
$rate = array(
  array('id_rate' => '1','id_user' => '9','id_product' => '1','rating' => '3','comment' => 'Qui nulla libero fugit vero iure.'),
  array('id_rate' => '2','id_user' => '5','id_product' => '2','rating' => '2','comment' => 'Aut assumenda beatae optio quidem voluptatem.'),
  array('id_rate' => '3','id_user' => '3','id_product' => '3','rating' => '2','comment' => 'Ut beatae aut autem sint eveniet accusantium tempore.'),
  array('id_rate' => '4','id_user' => '8','id_product' => '4','rating' => '2','comment' => 'Pariatur hic at debitis sed nihil quia.'),
  array('id_rate' => '5','id_user' => '2','id_product' => '5','rating' => '3','comment' => 'Aut dolorem qui maiores ut qui explicabo.'),
  array('id_rate' => '6','id_user' => '10','id_product' => '6','rating' => '4','comment' => 'Debitis eveniet alias in delectus sint.'),
  array('id_rate' => '7','id_user' => '2','id_product' => '7','rating' => '2','comment' => 'Excepturi eveniet et architecto est autem.'),
  array('id_rate' => '8','id_user' => '9','id_product' => '8','rating' => '4','comment' => 'Sequi autem et facere eum reiciendis ipsa.'),
  array('id_rate' => '9','id_user' => '8','id_product' => '9','rating' => '3','comment' => 'Quas dolorem provident impedit non soluta doloremque.'),
  array('id_rate' => '10','id_user' => '9','id_product' => '10','rating' => '4','comment' => 'Qui magnam deleniti eligendi beatae in.'),
  array('id_rate' => '11','id_user' => '5','id_product' => '11','rating' => '1','comment' => 'Qui qui quaerat impedit.'),
  array('id_rate' => '12','id_user' => '10','id_product' => '12','rating' => '1','comment' => 'Et consequatur beatae et labore doloribus labore.'),
  array('id_rate' => '13','id_user' => '7','id_product' => '13','rating' => '3','comment' => 'Vel sapiente aut quidem.'),
  array('id_rate' => '14','id_user' => '1','id_product' => '14','rating' => '3','comment' => 'Pariatur minima placeat quia suscipit.'),
  array('id_rate' => '15','id_user' => '7','id_product' => '15','rating' => '3','comment' => 'A aut id consectetur vel.'),
  array('id_rate' => '16','id_user' => '4','id_product' => '16','rating' => '2','comment' => 'Ea labore omnis tenetur aperiam eligendi aut.'),
  array('id_rate' => '17','id_user' => '5','id_product' => '17','rating' => '1','comment' => 'Ut voluptate id ullam molestiae enim.'),
  array('id_rate' => '18','id_user' => '5','id_product' => '18','rating' => '4','comment' => 'Illum quisquam libero explicabo tenetur nihil cum dolores.'),
  array('id_rate' => '19','id_user' => '10','id_product' => '19','rating' => '4','comment' => 'Maiores cum veritatis itaque.'),
  array('id_rate' => '20','id_user' => '7','id_product' => '20','rating' => '2','comment' => 'Fugit qui illo incidunt corporis ullam quam ab.'),
  array('id_rate' => '21','id_user' => '4','id_product' => '1','rating' => '2','comment' => 'Excepturi sed voluptates eius qui necessitatibus facilis.'),
  array('id_rate' => '22','id_user' => '3','id_product' => '2','rating' => '4','comment' => 'Aut ab necessitatibus quod alias repellat.'),
  array('id_rate' => '23','id_user' => '2','id_product' => '3','rating' => '4','comment' => 'Beatae non deleniti eos praesentium aut rerum.'),
  array('id_rate' => '24','id_user' => '7','id_product' => '4','rating' => '2','comment' => 'Blanditiis expedita dolore totam molestias voluptas.'),
  array('id_rate' => '25','id_user' => '2','id_product' => '5','rating' => '5','comment' => 'Dicta unde hic voluptatibus quas quis aspernatur assumenda.'),
  array('id_rate' => '26','id_user' => '10','id_product' => '6','rating' => '4','comment' => 'Eos deserunt iste modi provident sint ut atque.'),
  array('id_rate' => '27','id_user' => '10','id_product' => '7','rating' => '2','comment' => 'Qui et explicabo accusantium non assumenda.'),
  array('id_rate' => '28','id_user' => '10','id_product' => '8','rating' => '4','comment' => 'Dignissimos accusamus in ut mollitia accusantium debitis id expedita.'),
  array('id_rate' => '29','id_user' => '9','id_product' => '9','rating' => '5','comment' => 'Voluptatibus incidunt sunt est qui impedit.'),
  array('id_rate' => '30','id_user' => '7','id_product' => '10','rating' => '2','comment' => 'Dolore illo nostrum iste repellendus rerum mollitia repellendus.'),
  array('id_rate' => '31','id_user' => '1','id_product' => '11','rating' => '5','comment' => 'Nesciunt est soluta dolor tempore corrupti.'),
  array('id_rate' => '32','id_user' => '6','id_product' => '12','rating' => '3','comment' => 'Dolorem et in aut.'),
  array('id_rate' => '33','id_user' => '2','id_product' => '13','rating' => '4','comment' => 'Consequuntur incidunt cupiditate inventore.'),
  array('id_rate' => '34','id_user' => '4','id_product' => '14','rating' => '3','comment' => 'Natus laboriosam sequi id quia ipsa facilis.'),
  array('id_rate' => '35','id_user' => '4','id_product' => '15','rating' => '1','comment' => 'Expedita in eos nesciunt temporibus est maiores at pariatur.'),
  array('id_rate' => '36','id_user' => '1','id_product' => '16','rating' => '4','comment' => 'Similique in omnis autem ea odit quod.'),
  array('id_rate' => '37','id_user' => '1','id_product' => '17','rating' => '1','comment' => 'Sunt autem modi sit ut dolor et.'),
  array('id_rate' => '38','id_user' => '3','id_product' => '18','rating' => '5','comment' => 'Nihil aut provident et quia.'),
  array('id_rate' => '39','id_user' => '5','id_product' => '19','rating' => '5','comment' => 'Officiis aut saepe aut sunt.'),
  array('id_rate' => '40','id_user' => '9','id_product' => '20','rating' => '1','comment' => 'Est necessitatibus sit nostrum.')
);

/* `e-commerce-sql`.`users` */
$users = array(
  array('id_user' => '1','username' => 'vHarris','email' => 'Daniel.Jayson@Farrell.info','password' => '$2y$10$UDNws3Pi6q1DI61EDeRb.eeQejwNmfoumsKN5NHdPB7kq5H84tU8y','created_at' => '2024-10-11 23:51:47'),
  array('id_user' => '2','username' => 'Damian.Reichert','email' => 'Sherman59@hotmail.com','password' => '$2y$10$/./HTvXW79sxrURwnKxmLu2bVl.9RdjYxtRXabLeG6uKQGkD462dG','created_at' => '2024-10-11 23:51:47'),
  array('id_user' => '3','username' => 'Evalyn32','email' => 'Mckenzie66@Kuphal.com','password' => '$2y$10$1ObyN3E3D3Hw.V9kWv.aLe1GlPCpH7VK72lsQGRAvNFO2JibuhgDe','created_at' => '2024-10-11 23:51:48'),
  array('id_user' => '4','username' => 'Davin01','email' => 'Tyreek73@hotmail.com','password' => '$2y$10$XwK/0rF3/KMlATAPrBvYJ.T863aW5e4ftHYiEh45ZmX.kWKOyZYFO','created_at' => '2024-10-11 23:51:48'),
  array('id_user' => '5','username' => 'rFeil','email' => 'Brannon69@Murazik.net','password' => '$2y$10$xph1yAe7osRhWY4i53cn6uwiON6qLMlTraZ4mYy6nORWsFAmR8b8m','created_at' => '2024-10-11 23:51:48'),
  array('id_user' => '6','username' => 'iLubowitz','email' => 'xGerhold@gmail.com','password' => '$2y$10$vByePW9aQ4HUDSZRt6mx8OKPusb6nV8qY2I.b.Y5p5V5Wg0eShC2m','created_at' => '2024-10-11 23:51:48'),
  array('id_user' => '7','username' => 'Gabrielle.Spinka','email' => 'Lonnie41@Baumbach.com','password' => '$2y$10$Bdk7Osg3mUBV/QQvxYlRUebv2VaII.aU1WI/FoyyOuXPkWZpafmUW','created_at' => '2024-10-11 23:51:48'),
  array('id_user' => '8','username' => 'tWelch','email' => 'Shakira34@Satterfield.org','password' => '$2y$10$yu8i6ONsg0nu/tdFTXzC2.gm7rmnwdor764NJ037/zZbFWyU5xCAC','created_at' => '2024-10-11 23:51:48'),
  array('id_user' => '9','username' => 'Kathryne.Rolfson','email' => 'Herminio43@Mertz.com','password' => '$2y$10$EdhhJ8Ia29rzCKiDkFC3t.p7oN1YStU1ao43z8HmDDXlHQ2hmBr/u','created_at' => '2024-10-11 23:51:48'),
  array('id_user' => '10','username' => 'dHand','email' => 'fRutherford@Rau.com','password' => '$2y$10$5.qy88V9Y.9ntxwFS6.Ah.EmC9UTOt4yjoljMG1RyBb1k14rpFTEu','created_at' => '2024-10-11 23:51:48'),
  array('id_user' => '11','username' => 'Corwin.Aglae','email' => 'Kautzer.Emory@Hirthe.com','password' => '$2y$10$o.KDq6MWLM9eRKl1bjRwm.cipXEdTZ9ArY17psz4GMT0cQq2lK0e.','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '12','username' => 'pParisian','email' => 'rDenesik@Cummings.org','password' => '$2y$10$fM3s.8l4JwOqWH.tt3dMGuywtg6NLsFYD0z2eYyRXsU24J0.Ut1zO','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '13','username' => 'Schulist.Jamar','email' => 'Schroeder.Eugene@Lebsack.org','password' => '$2y$10$F2Ssk1FFvL9Km8vZZX4efuL040exP8ZfYEP1LKRg0fJ2wSNu2y13O','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '14','username' => 'Madison01','email' => 'Shaun47@gmail.com','password' => '$2y$10$TRepE8BOCwDGeN2jnLOtAOVlLNKfoqE1eqfA98bZgclHoYw8N8nd2','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '15','username' => 'iAuer','email' => 'Camden94@Witting.com','password' => '$2y$10$1lRVM0KcXZO4h7FNWP7ok.DZwInYy9KdPdvmWYia6s3GXo6Lk.dUC','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '16','username' => 'Durgan.Loraine','email' => 'xConsidine@gmail.com','password' => '$2y$10$pqSJHC0ns3vwTTDvduSFH./9abEvqxcPzeEm2rZvP50xwCzG16go6','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '17','username' => 'Ewell.Little','email' => 'Vivienne35@hotmail.com','password' => '$2y$10$JRfSN3qGa29.wtL7vboa4.FZapaiHtkETIFeb3OGOr1.Fzd678z5S','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '18','username' => 'Warren40','email' => 'Taya43@yahoo.com','password' => '$2y$10$CLVHK5yGt3Oghx3lpvI.X.CuK82CCJeHDLleq7pjBlU4nVyh8GPCu','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '19','username' => 'Goodwin.Betty','email' => 'Iliana19@Leffler.com','password' => '$2y$10$KlNCCTAiHxiXGZKT34MhMOhSB4B/NFIeuLSiUOkdaFQaS3566AfTS','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '20','username' => 'Julia05','email' => 'jBrakus@Davis.com','password' => '$2y$10$k3x5OySY3wtcp2KCK0cLbOWiTmxO0i7X4xfyKu9kbUr2YbVx8vvEG','created_at' => '2024-10-11 23:58:34'),
  array('id_user' => '21','username' => 'Art54','email' => 'Lizeth65@Boehm.org','password' => '$2y$10$jQ0yNxs8fRtCC32dejypqurJY8XnibrxwD9yeL08XINE8X8juFSGi','created_at' => '2024-10-12 00:00:16'),
  array('id_user' => '22','username' => 'Dario.Roberts','email' => 'vGerhold@gmail.com','password' => '$2y$10$/ZtS3j8g9XfR5OQ0h/UMY.WBgNpGF6SpRosCEM8Iu.nvRc.z1dpeK','created_at' => '2024-10-12 00:00:16'),
  array('id_user' => '23','username' => 'Blair.Stiedemann','email' => 'Lucius.Roob@Champlin.net','password' => '$2y$10$9kIfUQAqZsyNKx5qxaqcSOEAvP8.kssWtlRY.Z3nj3cOSPWzP6HfG','created_at' => '2024-10-12 00:00:16'),
  array('id_user' => '24','username' => 'tMayer','email' => 'jGreen@hotmail.com','password' => '$2y$10$DHq8lpuft3GcFMKUmQANl.4opa1M7Z5o6HXVeOrBE9FqwjqSeXMBe','created_at' => '2024-10-12 00:00:16'),
  array('id_user' => '25','username' => 'Tessie.Senger','email' => 'Bernard24@Bergnaum.com','password' => '$2y$10$H9lVHwvnRBr0uR651eQz9ORfcv.tz3wuW6gOV7BeuSWbCFJCzScMq','created_at' => '2024-10-12 00:00:16'),
  array('id_user' => '26','username' => 'Rosina71','email' => 'Priscilla.Cormier@yahoo.com','password' => '$2y$10$NoAEWGV21dO7jjvO1s9WieZrDCU8tTXXO.XT50o.mSQ.cEhfflSCq','created_at' => '2024-10-12 00:00:16'),
  array('id_user' => '27','username' => 'uLockman','email' => 'Janick.Moore@yahoo.com','password' => '$2y$10$EDv7GZZhECW1C1IBvQik1ebt4kaz4k1eWLvFwf0OSO5sIkBov4NZi','created_at' => '2024-10-12 00:00:16'),
  array('id_user' => '28','username' => 'Parisian.Jared','email' => 'Rocky58@VonRueden.biz','password' => '$2y$10$4MmcMrdcgw5z2TAolfLIJeUQFTVBEHC/eJ7.NKbxUfBSaswBQ.FhW','created_at' => '2024-10-12 00:00:17'),
  array('id_user' => '29','username' => 'Evans.Gulgowski','email' => 'Pat67@yahoo.com','password' => '$2y$10$pvLoCas9LdM.dcMfW0DDgOuuM/kulyfWl7Y2m5ErnDKsmFoT12X1u','created_at' => '2024-10-12 00:00:17'),
  array('id_user' => '30','username' => 'Dolores.Mante','email' => 'zRodriguez@gmail.com','password' => '$2y$10$wj.zs7lEZZj.HRE2jFpVx.RqGTiVvj5xdmVmMFIpVFPYbkZagNWF.','created_at' => '2024-10-12 00:00:17'),
  array('id_user' => '31','username' => 'fBauch','email' => 'lStark@yahoo.com','password' => '$2y$10$GjyXWu5dtlox2/G1E0RN5uvykcypstLqUMXgAhgT/PpIvf9r1j.ly','created_at' => '2024-10-12 00:02:29'),
  array('id_user' => '32','username' => 'Daphne10','email' => 'Euna.Heaney@yahoo.com','password' => '$2y$10$pHI3lqFz.hs7rkoo0VD4BOAXxildj6fOEkZlBM30izcpJaUijSw0W','created_at' => '2024-10-12 00:02:29'),
  array('id_user' => '33','username' => 'Rath.Icie','email' => 'Vada.Beier@Schuppe.com','password' => '$2y$10$gwiOOSYs9NhxQ57hUyopWuO29szOS5tZOMteNi/hZ1maqyYHsPNHG','created_at' => '2024-10-12 00:02:29'),
  array('id_user' => '34','username' => 'uHeathcote','email' => 'Boyer.Brayan@gmail.com','password' => '$2y$10$GJfXmo2WNHJXLKW2kPrYSuZCuPnaq3P5qvn1x4ewb5GXfGan.Xhai','created_at' => '2024-10-12 00:02:29'),
  array('id_user' => '35','username' => 'Schamberger.Ben','email' => 'Hazle.Labadie@hotmail.com','password' => '$2y$10$/Qs2bH1ykEP9Ksr.cCA5Bew3H1AbzvgMSO9673O4UX6ldgRhDHZuy','created_at' => '2024-10-12 00:02:29'),
  array('id_user' => '36','username' => 'Bins.Madeline','email' => 'Horace14@yahoo.com','password' => '$2y$10$1ptmtWWrMyWp9rS8zomzvOzPCQR08aJK70aFLGVXT1YQG.UQcgHMy','created_at' => '2024-10-12 00:02:29'),
  array('id_user' => '37','username' => 'Shyanne.Lind','email' => 'Jessika93@gmail.com','password' => '$2y$10$SboHpQE34t6f4GjNQigBm.Y4rlWKoTFfEUocIHTBBCtYStfKsK6P2','created_at' => '2024-10-12 00:02:29'),
  array('id_user' => '38','username' => 'Rosa13','email' => 'Kiley10@gmail.com','password' => '$2y$10$JlEPdEbcGOR5hUdi2tWN0.NVugoYRNYkiYVbI1Iw3KgN8YVbn.hJS','created_at' => '2024-10-12 00:02:29'),
  array('id_user' => '39','username' => 'Isai02','email' => 'rCormier@hotmail.com','password' => '$2y$10$JCzVF5gN769E8ejdHBiS1e5oZsceMsD1FK1hRCjRjCHKAzrZiFZya','created_at' => '2024-10-12 00:02:30'),
  array('id_user' => '40','username' => 'Ratke.Keeley','email' => 'Myrtie.Volkman@hotmail.com','password' => '$2y$10$wgDFH9ebZnQpGiccQMVzSetQCXHxvJ2Gk0erCrndwy0fAKg1nDi7.','created_at' => '2024-10-12 00:02:30'),
  array('id_user' => '41','username' => 'Bulah92','email' => 'Julio56@yahoo.com','password' => '$2y$10$4Gl2YdAH8Vyq0mXce6kSKuaoKYM5cBqYYJJkY6A3ParM7FS8ZkKxa','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '42','username' => 'iVolkman','email' => 'Kaya.Ebert@Sipes.info','password' => '$2y$10$uONYrsu9AV.IkNONUFl2NujklTQeH7DxJU.Vu5lbCuU9dXPTo6S4O','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '43','username' => 'Aditya75','email' => 'Maggie.Rice@Dickinson.net','password' => '$2y$10$D88KciuGtZ2zMeSLOagJ5euN7nkBdHiAIbXQ4pMkQZ3JUp803Qg.y','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '44','username' => 'Otis69','email' => 'Saige.Auer@hotmail.com','password' => '$2y$10$ppzBjIFfjFNQU3P29AyBgu1XQcXZTf9b/iho8yp0ntfBKjIkFSe3y','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '45','username' => 'Ruth.Heidenreich','email' => 'Vicky.Lemke@Gulgowski.com','password' => '$2y$10$X1zQN0XOJsySBS00s/gope0Alv8LedEdAPTC9DwitVKHxVpIeuedm','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '46','username' => 'Abernathy.Candace','email' => 'Rogahn.Juana@Gorczany.com','password' => '$2y$10$JoM5t0f5ycj0WEZZiQsbkux6r/si2KXeKinm8VXlmJPwYavVFgYtu','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '47','username' => 'Travis07','email' => 'Sven.Schamberger@Marquardt.net','password' => '$2y$10$b1mp9muQ0oi2K2fHfW5Ij.l0q8Er5jSo/aAaoZNTXDTCGvxuFb9IK','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '48','username' => 'bBreitenberg','email' => 'dFisher@yahoo.com','password' => '$2y$10$KaC0NM0qEjEkDaJZH9wBIeWt8rHEu0hVPZZMj2Gt2Vv4zOT6AEMIi','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '49','username' => 'Candelario33','email' => 'Theresa.Hoeger@hotmail.com','password' => '$2y$10$Vlgdviq5dr2WwKpAZxjeueR4De8TlMV53m/UJNgWDMV7sTt6bof4S','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '50','username' => 'xZulauf','email' => 'Hegmann.Demetrius@Bode.com','password' => '$2y$10$RTC4sTnfammI98OK74xLEuA88OjNPrF03xeiEFtJia9Px3TTDCxmK','created_at' => '2024-10-12 00:07:04'),
  array('id_user' => '51','username' => 'Kellen.Lowe','email' => 'Macie44@Padberg.com','password' => '$2y$10$BlrFjQmMbk26JGHLCappcurMKBR2jBz43u5RzBnQBaGxdLqTvwIXS','created_at' => '2024-10-12 00:10:53'),
  array('id_user' => '52','username' => 'Shania95','email' => 'Lemke.Cyrus@Tromp.com','password' => '$2y$10$bOWEZZ6Aa6OEJx1w.IWzA.Uu9qrhJDENp51cUtuFdDFKIWF30mihq','created_at' => '2024-10-12 00:10:53'),
  array('id_user' => '53','username' => 'Howell.Weissnat','email' => 'Ellie.Wisozk@Huels.com','password' => '$2y$10$UXe.Ve1Pdhf6cCjmd5AF7.Pfr2yBuZdBi0jVPikWIcvx.PT0SnrIi','created_at' => '2024-10-12 00:10:53'),
  array('id_user' => '54','username' => 'Domenica55','email' => 'Ashlynn40@Shields.net','password' => '$2y$10$xaSNfuJhfFP776oMBCLL5.kE8Adu2cVLGQXSBuB1dA8CD7fh7Ce7W','created_at' => '2024-10-12 00:10:54'),
  array('id_user' => '55','username' => 'Arely83','email' => 'Weimann.Amy@Strosin.com','password' => '$2y$10$P64ikfv9pmpk2wRtaS0pHu/XzYmogHjBO75Rys9BNNTsp4TWhS93q','created_at' => '2024-10-12 00:10:54'),
  array('id_user' => '56','username' => 'Daren.Conroy','email' => 'gKris@Mitchell.com','password' => '$2y$10$Cjr/Srg.4NLysOT0SXVCXOfFgg7kdKMGDteQKtrlRpRyS8NwCfCsm','created_at' => '2024-10-12 00:10:54'),
  array('id_user' => '57','username' => 'Stroman.Sam','email' => 'Wolff.Keven@hotmail.com','password' => '$2y$10$cfbGFEq8edymDRZL/DUU0uxiGiXtizzUJXn7yECnq8yBIeo.mneHS','created_at' => '2024-10-12 00:10:54'),
  array('id_user' => '58','username' => 'Paucek.Elvie','email' => 'sTurner@hotmail.com','password' => '$2y$10$4OJ9ncd7BmMhctuge/Ee2eKU.IYpSO3vhMGAYXxXQig1aCcqDhvzy','created_at' => '2024-10-12 00:10:54'),
  array('id_user' => '59','username' => 'Rogahn.Christelle','email' => 'Jacklyn71@Howell.net','password' => '$2y$10$y29C33P5Z6OQLhrw.Efl5.VVp/M19AI9WI7GfkqAu9rVK/zNqaKaS','created_at' => '2024-10-12 00:10:54'),
  array('id_user' => '60','username' => 'uHamill','email' => 'Aditya38@Dietrich.com','password' => '$2y$10$CsrZ7QPZ7nAWjUcHx4ClUOsuR.n9ciC3N9JBENW1.V8dmVDm2RSXa','created_at' => '2024-10-12 00:10:54'),
  array('id_user' => '61','username' => 'oFay','email' => 'Friedrich63@Feeney.com','password' => '$2y$10$SPnecX3ACoVNrZKsstx7beDkvJxJghUATY8tWYioLC2t7NSmF/v1i','created_at' => '2024-10-12 00:13:26'),
  array('id_user' => '62','username' => 'Walker.Jeanie','email' => 'Sanford02@gmail.com','password' => '$2y$10$vie6p6SYg0diwKdbLpEHd..SXzHHgCmf2NUrC8dfmxTxRUcHTfpC.','created_at' => '2024-10-12 00:13:26'),
  array('id_user' => '63','username' => 'Kennedy82','email' => 'Langworth.Werner@Vandervort.org','password' => '$2y$10$uBLsO3Z9EErOzxzNKSW/f.qu1HrJ.GXyzHefbjznUCaflHjDLvzLa','created_at' => '2024-10-12 00:13:26'),
  array('id_user' => '64','username' => 'Kertzmann.Kameron','email' => 'Lakin.Geovanny@yahoo.com','password' => '$2y$10$bPo/t79OwC15Nn9jb2LlxeVsj/5q5Gd6TmTODBGItaNIa3fYqmLwe','created_at' => '2024-10-12 00:13:26'),
  array('id_user' => '65','username' => 'Taya59','email' => 'Wintheiser.Ozella@Hessel.biz','password' => '$2y$10$/dSF0XrDz0Ei6RmRUj6K/.W5MXj3a4.whe9mZLYas/TeNJya4ku3C','created_at' => '2024-10-12 00:13:26'),
  array('id_user' => '66','username' => 'Electa55','email' => 'sAbbott@hotmail.com','password' => '$2y$10$lp6RzDU6AHyRMHB3uBko5.EcvIaSAsL0m8YP3u3HScGlAxc3PfP/2','created_at' => '2024-10-12 00:13:26'),
  array('id_user' => '67','username' => 'Damion.Lebsack','email' => 'Doyle.Rogahn@Steuber.info','password' => '$2y$10$8xzxrCBorv3NG4bB4YF1XeIE0aKeZjNPiTvvMq7BkRnGUP/.eZcN6','created_at' => '2024-10-12 00:13:26'),
  array('id_user' => '68','username' => 'Aditya94','email' => 'Borer.Bud@gmail.com','password' => '$2y$10$ApxVHNj6SGfE.J6CfKWNeOW5M4FMVCTmVl6mGk/J0Unlgx9HQCgc.','created_at' => '2024-10-12 00:13:26'),
  array('id_user' => '69','username' => 'Jerde.Mattie','email' => 'mHoeger@hotmail.com','password' => '$2y$10$qdYhCIIk71lqJjA6n7NcCOnZ1mtgEdeCxWr3SRGjXYEMNk3XOu8aa','created_at' => '2024-10-12 00:13:27'),
  array('id_user' => '70','username' => 'Elna.Johnston','email' => 'Lance84@gmail.com','password' => '$2y$10$3YKIkg5M.EP.uha8I2ExQu2if7Bn7vwL8TZj4BsDYFlHpNDjL6asC','created_at' => '2024-10-12 00:13:27')
);
